### ISSUE TITLE
Unable to get tegra-cam-caffe.py tegra-cam.py？

### ISSUE THREAD

**Issue by gzz1529657064** [jkjung-avt/tensorrt_demos#10]
I read your blog 'How to Capture Camera Video and Do Caffe Inferencing with Python on Jetson TX2' and 'How to Capture and Display Camera Video with Python on Jetson TX2 '
These two files cannot be obtained.  I don't want to go through the firewall. Can you send me files by email? I suggest you place a new link without going through the firewall. Thanks!

**Comment by jkjung-avt** [comment]
The source code is on GitHub.  Since you are able to post comments on GitHub, you should be able to access the code directly. 

https://gist.github.com/jkjung-avt/86b60a7723b97da19f7bfa3cb7d2690e
https://gist.github.com/jkjung-avt/d408aaabebb5b0041c318f4518bd918f
