### ISSUE TITLE
memory leaks with videocapture

### ISSUE THREAD

**Issue by PythonImageDeveloper** [jkjung-avt/tensorrt_demos#101]
I am using to capture the video from rtsp stream. It has no problem to capture and read the stream. But I found, the function "read(InputArrray Image)" cause the memory leak. The memory goes up slowly, about one MB for two or three hours. But it keep going up. I am using it for severy months continually. so it is seriouly problem for me.
I used [open_cam_rtsp()](https://github.com/jkjung-avt/tensorrt_demos/blob/master/utils/camera.py#L62) with nano.

I installed Jetpack 4.2.2 and opencv 3.4.6 from source with gstreamer 1.14.5 support.
How can I solve this problem?

**Comment by jkjung-avt** [comment]
This problem is not related to TensorRT at all.  I have to say sorry.  I'm not able to look into this problem now.
