### ISSUE TITLE
Black & white image

### ISSUE THREAD

**Issue by jeansely** [jkjung-avt/tensorrt_demos#102]
Hi,
For black and white images, what parts of the code should be changed?
Many Thanks.

**Comment by jkjung-avt** [comment]
Take trt_ssd.py as an example.  You could add a line of code to convert your black and white image to BGR by adding the following code before calling [trt_ssd.detect()](https://github.com/jkjung-avt/tensorrt_demos/blob/master/trt_ssd.py#L62).

```
        img = cv2.cvtColor(img, cv2.COLOR_GRAY2RGB)
```
