### ISSUE TITLE
typeerror: a bytes-like object is required, not 'nonetype'

### ISSUE THREAD

**Issue by Darshcg** [jkjung-avt/tensorrt_demos#105]
I am trying Demo 4 on my Jetson Nano

I am facing error wrt Converting onnx to trt.
Here is the error
![image](https://user-images.githubusercontent.com/48723743/80640545-30102480-8a81-11ea-8b3e-52b186ee3f52.png)

How can I resolve this?

**Comment by jkjung-avt** [comment]
I think the error `[TensorRT] ERROR: FAILED_ALLOCATION: std::bad_alloc` simply means TensorRT failed to allocate memory.

Please close your web browsers and other memory-hogging applications and try again.  If that still doesn't work, adding a swap might likely help.  Reference: [Setting up Jetson Nano: The Basics](https://jkjung-avt.github.io/setting-up-nano/)

**Comment by Darshcg** [comment]
Thank you so much, Jung. I resolved it by closing all other applications. 
Btw After running yolov3-416 with TRT, I was getting 3 FPS, and yolov3-tiny-416 with TRT I was getting 16 FPS.
Btw how to run .weights and .cfg as it is(without TRT)? I want to test the Speed.

Thanks in Advance

**Comment by jkjung-avt** [comment]
https://jkjung-avt.github.io/yolov3/
