### ISSUE TITLE
TensorRT 5.X / 6.X Batch Size Problem

### ISSUE THREAD

**Issue by PythonImageDeveloper** [jkjung-avt/tensorrt_demos#109]
Hi @jkjung-avt 
I asked the problem of batch size in TensorRT, and they answer me this:

> I will recommend you to use TRT 7 and use optimization profiles to optimize for multiple different batch sizes.

[https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#opt_profiles](url)

Do you know about this concept, How I do to your codes? 
Thanks

**Comment by jkjung-avt** [comment]
No, I have not used "Optimization Profiles" for TensorRT before.

**Comment by PythonImageDeveloper** [comment]
You told me to change max_batch_size >1 and this way don't work for batch size > 1, woke like one bu one for batch of data.
