### ISSUE TITLE
Custom frozen graph gives the following error

### ISSUE THREAD

**Issue by saurabbhsp** [jkjung-avt/tensorrt_demos#117]
I face the following error while transfer learning a pre-trained model on mobilenet_v1_pets

Traceback (most recent call last):
  File "build_engine.py", line 218, in <module>
    main()
  File "build_engine.py", line 195, in main
    spec)
  File "build_engine.py", line 173, in add_plugin
    graph.find_nodes_by_name("Input")[0].input.remove("image_tensor:0")
ValueError: remove(x): x not in container

For the generation of frozen graphs, I am using export_Inference_graph.py

PS:- The node was Cast instead of image_tensor:0

**Comment by jkjung-avt** [comment]
Try commenting out this line from the code.

`graph.find_nodes_by_name("Input")[0].input.remove("image_tensor:0")`

**Comment by jkjung-avt** [comment]
Has the issue been resolved?

**Comment by saurabbhsp** [comment]
Yes it is resolved. Thanks for your help. The issue with custom training is that you need to train the model with TF-1.10, using newer versions results in the above mentioned error.

Thanks for your help.
