### ISSUE TITLE
camera resolution

### ISSUE THREAD

**Issue by PatrikPatrik2** [jkjung-avt/tensorrt_demos#122]
I use an on-board camera, and I can change the camera resolution using the -- width 1200 --height 720
It will display a large image on the screen and make object detection, but using 720 and especially 1080 resolution it becomes obvious that the image is not using the defined resolution, instead it seems to upscale an image with low resolution - resulting in a large image with low resolution (large pixels).
Is there some way to correct this?

**Comment by jkjung-avt** [comment]
I think this question is not directly related to this repository.  I'd suggest you to post such a question to [NVIDIA Developer Forum](https://forums.developer.nvidia.com/c/agx-autonomous-machines/55).

**Comment by PatrikPatrik2** [comment]
OK, thanks
