### ISSUE TITLE
TypeError: buffer is too small for requested array

### ISSUE THREAD

**Issue by Darshcg** [jkjung-avt/tensorrt_demos#127]
While I run: python3 yolov3_to_onnx.py --model yolov3-288
I am getting  error like this:
File "yolov3_to_onnx.py", line 375, in _load_one_param_type buffer=self.weights_file.read(param_size * 4))
TypeError: buffer is too small for requested array

Can you please help to resolve this
Thanks in advance

**Comment by jkjung-avt** [comment]
Are you using the code with your own custom trained model?

**Comment by Darshcg** [comment]
Yes

**Comment by Darshcg** [comment]
And also if I run:  "python3 eval_yolov3.py --model yolov3-288" I am getting TypeError: 'module' object is not callable. Can you please help to resolve the same

**Comment by jkjung-avt** [comment]
For your own custom YOLOv3 model, you'll need to modify "category_num" in the code by yourself.  Please refer to https://github.com/jkjung-avt/tensorrt_demos/issues/55 or other similar issues in this repository.

**Comment by Darshcg** [comment]
Thank you
