### ISSUE TITLE
yolov3-416.trt no such file or directory

### ISSUE THREAD

**Issue by AntoineHoe** [jkjung-avt/tensorrt_demos#134]
Hello,
I met this error while I was testing the dog image and I can't figure it out.
May someone give me an hint ?
Thanks !

![image](https://user-images.githubusercontent.com/26748640/84578179-30f7de00-adc3-11ea-95b0-aa70dc6eaab5.png)

**Comment by jkjung-avt** [comment]
Did you follow the steps in [Demo #4: YOLOv3](https://github.com/jkjung-avt/tensorrt_demos#yolov3) and build the TensorRT engine?  After finishing step 3, the file "yolov3_onnx/yolov3-416.trt" should be built.

```
$ python3 onnx_to_tensorrt.py --model yolov3-416
```

**Comment by AntoineHoe** [comment]
What an absent-minded I am, I forgot this line.
But when I did, I reach this error and I did see it occur in the other issues :/
![Screenshot from 2020-06-14 12-50-45](https://user-images.githubusercontent.com/26748640/84591683-b9689400-ae40-11ea-840c-e44f27c98f3b.png)

**Comment by jkjung-avt** [comment]
Make sure you are using onnx==1.4.1.

```
$ pip3 show onnx
```

**Comment by AntoineHoe** [comment]
Yeah, at least I succed this step
![image](https://user-images.githubusercontent.com/26748640/84592525-993bd380-ae46-11ea-858e-64c1fafc52c7.png)

**Comment by jkjung-avt** [comment]
https://github.com/onnx/onnx/issues/2534

p.s. I use protobuf-3.8.0.

**Comment by AntoineHoe** [comment]
Great, it's working on the dog picture, thanks !

**Comment by jkjung-avt** [comment]
https://github.com/jkjung-avt/tensorrt_demos/issues/539#issuecomment-1119218462
