### ISSUE TITLE
Layer of type yolo not supported, skipping ONNX node generation.

### ISSUE THREAD

**Issue by stanislavkuskov** [jkjung-avt/tensorrt_demos#138]
Hi! Thank You for this example!

When i run python3 yolov3_to_onnx.py --model yolov3-608 its write me "Layer of type yolo not supported, skipping ONNX node generation."

And I still wait long time. But example from tensorrt work fine ()
PS. Jetson tx2 with jetpack 4.4 (cuda 10.2, cudnn 7.6.5, tensorrt 7, onnx 1.6.0)
PSPS. I try with onnx 1.4.1 but have same message.

**Comment by jkjung-avt** [comment]
The "Layer of type yolo not supported..." warning message is printed by [this line of code](https://github.com/jkjung-avt/tensorrt_demos/blob/master/yolov3_onnx/yolov3_to_onnx.py#L493) and could be safely ignored.

At inference time, functionalities of those skipped layers are handled by the [PostProcessYOLO class](https://github.com/jkjung-avt/tensorrt_demos/blob/master/utils/yolov3.py#L68).
