### ISSUE TITLE
ModuleNotFoundError: No module named 'pycuda'

### ISSUE THREAD

**Issue by aditjha** [jkjung-avt/tensorrt_demos#139]
Hi, I ran the ./install_pycuda.sh and I saw the following: 
*** WARNING: nvcc not in path.
*** May need to set CUDA_INC_DIR for installation to succeed.
and the installation finished.  If I type python3 in terminal and import pycuda, it works, however when I try to test the model inference I get 

ModuleNotFoundError: No module named 'pycuda'.

I am using cuda 10.0 on a jetson nano and nvcc --version returns correct information. If I could please get some help I would be really thankful.

**Comment by jkjung-avt** [comment]
What was the problem?  Or how did you resolve the issue?
