### ISSUE TITLE
Trying to incorporate trt_yolov3.py script in another python script

### ISSUE THREAD

**Issue by aditjha** [jkjung-avt/tensorrt_demos#143]
Hello,

I am trying to be able to call the trt_yolov3.py script from inside another python script while passing arguments like it currently takes from the command line. I am able to `import trt_yolov3` however I don't know how I can pass arguments to the main function within a python script, would I have to modify the code so that the `main` function takes in parameters?

**Comment by jkjung-avt** [comment]
There are multiple ways to solve your problem.  For example, you could use SimpleNamespace to replace args in the original code:

```
def trt_yolov3_main(args):  # rename main() as trt_yolov3_main() to avoid function name collision
    # args = parse_args()  -> comment out this line
    if args.category_num <= 0:
        raise SystemExit('Bad category_num: %d!' % args.category_num)
    ......
```

In your own code, initialize "args" with SimpleNamespace:

```
from types import SimpleNamespace

args = SimpleNamespace()
args.use_file = True
args.filename = 'test.mp4'  # use this video file as input
args.model = 'yolov3-416'
trt_yolov3_main(args)
```
