### ISSUE TITLE
Error when run with deepstream-app

### ISSUE THREAD

**Issue by subzeromot** [jkjung-avt/tensorrt_demos#155]
I run deepstream-app with TRT_ssd_mobilenet_v2_coco.bin but error:
ERROR                nvinfer gstnvinfer.cpp:596:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::parseBoundingBox() <nvdsinfer_context_impl_output_parsing.cpp:59> [UID = 1]: Could not find output coverage layer for parsing objects
ERROR                nvinfer gstnvinfer.cpp:596:gst_nvinfer_logger:<primary_gie> NvDsInferContext[UID 1]: Error in NvDsInferContextImpl::fillDetectionOutput() <nvdsinfer_context_impl_output_parsing.cpp:573> [UID = 1]: Failed to parse bboxes
![Screenshot from 2020-07-20 12-25-13](https://user-images.githubusercontent.com/7932656/87902628-56dc6680-ca84-11ea-87f8-70f5c780d5ef.png)

**Comment by jkjung-avt** [comment]
DeepStream SDK probably defined a different file format for TensorRT engines.  Please use DeepStream's built-in tools to build your TensorRT engine instead.

Reference: https://github.com/jkjung-avt/tensorrt_demos/issues/48#issuecomment-582193008
