### ISSUE TITLE
Error while convert custom object detection (darknet yolov4) from onnx to trt. AttributeError: 'NoneType' object has no attribute 'serialize'

### ISSUE THREAD

**Issue by maxjundo** [jkjung-avt/tensorrt_demos#161]
Hi!
Follow your [demo#5](https://github.com/jkjung-avt/tensorrt_demos#yolov4) to convert my own custom object detection (yolov4 darknet) with 1 class, but get error, while use `python3 onnx_to_tensorrt.py --model yolov4-416`:

> Loading ONNX file from path yolov4-416.onnx...
> Beginning ONNX file parsing
> Completed parsing of ONNX file
> Building an engine; this may take a while...
> [TensorRT] ERROR: ../builder/cudnnBuilderWeightConverters.cpp (541) - Misc Error in operator(): 1 (Weights are outside of fp16 range. A possible fix is to retrain the model with regularization to bring the magnitude of the weights down.)
> [TensorRT] ERROR: ../builder/cudnnBuilderWeightConverters.cpp (541) - Misc Error in operator(): 1 (Weights are outside of fp16 range. A possible fix is to retrain the model with regularization to bring the magnitude of the weights down.)
> Completed creating engine
> Traceback (most recent call last):
>   File "onnx_to_tensorrt.py", line 121, in <module>
>     main()
>   File "onnx_to_tensorrt.py", line 117, in main
>     _ = build_engine(onnx_file_path, engine_file_path, args.verbose)
>   File "onnx_to_tensorrt.py", line 96, in build_engine
>     f.write(engine.serialize())
> AttributeError: 'NoneType' object has no attribute 'serialize'

I also try convert to onnx using that: 
`python3 yolo_to_onnx.py --model yolov4-416 --category_num 1`

May you advise something to resolve this issue?

P.S. try that config and weights on colabs (darknet yolo) and inference work ok.

**Comment by jkjung-avt** [comment]
> [TensorRT] ERROR: ../builder/cudnnBuilderWeightConverters.cpp (541) - Misc Error in operator(): 1 (Weights are outside of fp16 range. A possible fix is to retrain the model with regularization to bring the magnitude of the weights down.)

The "Weights are outside of fp16 range" error means that your trained model contains at least 1 weight (or a trainable parameter of a layer) which is fine in FP32 format but is too large to be represented in FP16 format.  There are 2 ways you could try to get around this:

1. Run TensorRT in FP32 mode (would be slower than FP16).  You could do that by setting `builder.fp16_mode = False` ([here](https://github.com/jkjung-avt/tensorrt_demos/blob/master/yolo/onnx_to_tensorrt.py#L72)) and re-run "onnx_to_tensorrt.py".

2. Re-train your custom model with a higher [weight decay value](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4-custom.cfg#L12).  Hopefully, your re-trained custom model wouldn't contain weights which are outside of FP16 range then.
