### ISSUE TITLE
opencv dpendency for compile of yolo4?

### ISSUE THREAD

**Issue by ozett** [jkjung-avt/tensorrt_demos#162]
i have little experience with discuss, but found the post marked as spam in my own profile.
i unmarked it. twice, but still marked as spam.

https://jkjung-avt.github.io/yolov4/   --> original post was:

"why do you mention that you had opencv installed on the nano to compile yolov4?
i was looking for a way to use the succesful compiled v4 lib with the installed opencv on the nano, but found no way.
my compile went ok but doesnt seem to need opencv, but it was already there and i dont looked into all warning.
is there a way to manually move the yolov4/darknet-lib into existing opencv 4.1.xx on the nano? thx."

**Comment by jkjung-avt** [comment]
For [YOLOv4 on Jetson Nano](https://jkjung-avt.github.io/yolov4/):

Since I'd set `OPENCV=1` in the "Makefile", it's necessary to make sure libopencv* are installed properly on the system.  I think the resulting "darknet" executable would require libopencv*.so to run.
