### ISSUE TITLE
How to make batch inferences？

### ISSUE THREAD

**Issue by Baenny** [jkjung-avt/tensorrt_demos#163]
Hi，how to infer multiple images in batch using yolov3 trt model? 
I searched some similar questions in the https://github.com/NVIDIA/TensorRT, but I didn't find any valid answers.
Now I set builder.max_batch_size = 4 in onnx_to_tensorrt.py , and I have no idea how to infer.
May you advise something to resolve this issue?

**Comment by jkjung-avt** [comment]
You need to modify [utils/yolo.py](https://github.com/jkjung-avt/tensorrt_demos/blob/master/utils/yolo.py):

* in the preprocess part, stack 4 preprocessed images into 1 tensor before feeding it to the inference function,
* in the postproessing part, you need to split the outputs for the 4 images and postprocess one by one.

**Comment by Baenny** [comment]
Thanks for your reply! I'll try it.
