### ISSUE TITLE
TypeError: 1.0 has type numpy.float32, but expected one of: int, long, float

### ISSUE THREAD

**Issue by derek285** [jkjung-avt/tensorrt_demos#164]
hi 

For YOLOv4 on Jetson:

tensorrt version: '7.1.3.0'

$ python3 yolo_to_onnx.py --model yolov4-416

Parsing DarkNet cfg file...
Building ONNX graph...
Traceback (most recent call last):
  File "yolo_to_onnx.py", line 957, in <module>
    main()
  File "yolo_to_onnx.py", line 940, in main
    verbose=True)
  File "yolo_to_onnx.py", line 456, in build_onnx_graph
    params)
  File "yolo_to_onnx.py", line 287, in load_upsample_scales
    name, TensorProto.FLOAT, shape, data)
  File "/home/yxavier/.local/lib/python3.6/site-packages/onnx/helper.py", line 173, in make_tensor
    getattr(tensor, field).extend(vals)
TypeError: 1.0 has type numpy.float32, but expected one of: int, long, float

thanks for reply

**Comment by jkjung-avt** [comment]
Reference: https://github.com/jkjung-avt/tensorrt_demos/issues/53#issuecomment-581253908

Please update your python3 "protobuf" module.

**Comment by derek285** [comment]
same error after update:
protoc --version
libprotoc 3.12.3

**Comment by derek285** [comment]
same error after update
protoc --version
libprotoc 3.12.3

**Comment by jkjung-avt** [comment]
What about `pip3 show protobuf`?

**Comment by derek285** [comment]
pip3 show protobuf

Name: protobuf
Version: 3.0.0
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: None
Author-email: None
License: New BSD License
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: onnx, uff

**Comment by derek285** [comment]
pip3 show protobuf


Name: protobuf
Version: 3.0.0
Summary: Protocol Buffers
Home-page: https://developers.google.com/protocol-buffers/
Author: None
Author-email: None
License: New BSD License
Location: /usr/lib/python3/dist-packages
Requires: 
Required-by: onnx, uff

**Comment by jkjung-avt** [comment]
Please update it.  I would suggest 3.8.0.

**Comment by derek285** [comment]
cool,it works,thanks a lot
