### ISSUE TITLE
Change of Threshold value of detection in case of custom yolov3 and yolov4 Tensorrt implementation? 

### ISSUE THREAD

**Issue by Farjad3253** [jkjung-avt/tensorrt_demos#166]
Hello! I want to ask that how can we change the threshold value of detection in case of custom yolov4 tensorrt implementation?

**Comment by jkjung-avt** [comment]
Set "conf_th" here: https://github.com/jkjung-avt/tensorrt_demos/blob/41e388b2b3acbf3efa4d27c168ceabfec1e37049/trt_yolo.py#L108
