### ISSUE TITLE
Hi I have tensorrt 7.0.0 , I want to implement ssd mobilenet v2 on the same with T4. Kindly help

### ISSUE THREAD

**Issue by Abrahamma97** [jkjung-avt/tensorrt_demos#169]
Hi I have tensorrt 7.0.0 , I want to implement ssd mobilenet v2 on the same with T4. Kindly help

**Comment by jkjung-avt** [comment]
Please refer to: https://github.com/jkjung-avt/tensorrt_demos/blob/master/README_x86.md

**Comment by Abrahamma97** [comment]
I have already . I am unable to do these steps ...
$ export TRT_DIR=/usr/local/TensorRT-5.1.5.0
$ sudo pip3 install ${TRT_DIR}/python/tensorrt-5.1.5.0-cp36-none-linux_x86_64.whl
$ sudo pip3 install ${TRT_DIR}/uff/uff-0.6.3-py2.py3-none-any.whl
$ sudo pip3 install ${TRT_DIR}/graphsurgeon/graphsurgeon-0.4.1-py2.py3-none-any.whl
I have tensorrt here
/usr/src/tensorrt$ ls
bin  data  samples

**Comment by jkjung-avt** [comment]
1. Replace `$ export TRT_DIR=/usr/local/TensorRT-5.1.5.0` with `$ export TRT_DIR=/usr/src/tensorrt`.
2. Replace version numbers of pip3 tensorrt, uff and graphsurgeon with the ones you are using.
3. Find where you have installed "libnvinfer*.so".  Add that path into your LD_LIBRARY_PATH.

**Comment by Abrahamma97** [comment]
Can you tell me how to Replace version numbers of pip3 tensorrt, uff and graphsurgeon with the ones you are using.
export TRT_DIR=/usr/src/tensorrt
bhmk@bhmk-PowerEdge-R740xd:~$ sudo pip3 install ${TRT_DIR}/python/tensorrt-7.0.0-cp36-none-linux_x86_64.whl
[sudo] password for bhmk: 
The directory '/home/bhmk/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/home/bhmk/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement '/usr/src/tensorrt/python/tensorrt-7.0.0-cp36-none-linux_x86_64.whl' looks like a filename, but the file does not exist
Processing /usr/src/tensorrt/python/tensorrt-7.0.0-cp36-none-linux_x86_64.whl
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 342, in run
    requirement_set.prepare_files(finder)
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python3/dist-packages/pip/req/req_set.py", line 620, in _prepare_file
    session=self.session, hashes=hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 809, in unpack_url
    unpack_file_url(link, location, download_dir, hashes=hashes)
  File "/usr/lib/python3/dist-packages/pip/download.py", line 715, in unpack_file_url
    unpack_file(from_path, location, content_type, link)
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 617, in unpack_file
    flatten=not filename.endswith('.whl')
  File "/usr/lib/python3/dist-packages/pip/utils/__init__.py", line 500, in unzip_file
    zipfp = open(filename, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/usr/src/tensorrt/python/tensorrt-7.0.0-cp36-none-linux_x86_64.whl'

**Comment by jkjung-avt** [comment]
Please refer to NVIDIA's official TensorRT installation guide: https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html

It seems that you did not download the complete package of TensorRT.  Please follow the procedure in the official documentation and make sure tensorrt, uff and graphsurgeon are installed properly.

**Comment by Abrahamma97** [comment]
I have done and pip installed everything
Re-build libflattenconcat.so from TensorRT's 'python/uff_ssd' sample source code. => is this necessary to do

**Comment by jkjung-avt** [comment]
It is not necessary fr TensorRT 7.

**Comment by Abrahamma97** [comment]
./build_engines.sh
+ for model in ssd_mobilenet_v1_coco ssd_mobilenet_v1_egohands ssd_mobilenet_v2_coco ssd_mobilenet_v2_egohands
+ python build_engine.py ssd_mobilenet_v1_coco
WARNING:tensorflow:From /usr/lib/python2.7/dist-packages/uff/converters/tensorflow/conversion_helpers.py:18: The name tf.GraphDef is deprecated. Please use tf.compat.v1.GraphDef instead.

WARNING:tensorflow:From /usr/lib/python2.7/dist-packages/graphsurgeon/_utils.py:2: The name tf.NodeDef is deprecated. Please use tf.compat.v1.NodeDef instead.

WARNING:tensorflow:From /usr/lib/python2.7/dist-packages/graphsurgeon/StaticGraph.py:125: The name tf.gfile.GFile is deprecated. Please use tf.io.gfile.GFile instead.

WARNING: To create TensorRT plugin nodes, please use the `create_plugin_node` function instead.
UFF Version 0.6.5
=== Automatically deduced input nodes ===
[name: "Input"
op: "Placeholder"
attr {
  key: "shape"
  value {
    shape {
      dim {
        size: 1
      }
      dim {
        size: 3
      }
      dim {
        size: 300
      }
      dim {
        size: 300
      }
    }
  }
}
]
=========================================

Using output node NMS
Converting to UFF graph
Warning: No conversion function registered for layer: NMS_TRT yet.
Converting NMS as custom op: NMS_TRT
WARNING:tensorflow:From /usr/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py:179: The name tf.AttrValue is deprecated. Please use tf.compat.v1.AttrValue instead.

Warning: No conversion function registered for layer: FlattenConcat_TRT yet.
Converting concat_box_conf as custom op: FlattenConcat_TRT
Traceback (most recent call last):
  File "build_engine.py", line 219, in <module>
    main()
  File "build_engine.py", line 202, in main
    debug_mode=DEBUG_UFF)
  File "/usr/lib/python2.7/dist-packages/uff/converters/tensorflow/conversion_helpers.py", line 178, in from_tensorflow
    debug_mode=debug_mode)
  File "/usr/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 94, in convert_tf2uff_graph
    uff_graph, input_replacements, debug_mode=debug_mode)
  File "/usr/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 79, in convert_tf2uff_node
    op, name, tf_node, inputs, uff_graph, tf_nodes=tf_nodes, debug_mode=debug_mode)
  File "/usr/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 47, in convert_layer
    return cls.registry_[op](name, tf_node, inputs, uff_graph, **kwargs)
  File "/usr/lib/python2.7/dist-packages/uff/converters/tensorflow/converter_functions.py", line 21, in convert_placeholder
    dtype = tf2uff.convert_tf2numpy_dtype(tf_node.attr['dtype'].type)
  File "/usr/lib/python2.7/dist-packages/uff/converters/tensorflow/converter.py", line 103, in convert_tf2numpy_dtype
    return tf.as_dtype(dtype).as_numpy_dtype
  File "/home/bhmk/.local/lib/python2.7/site-packages/tensorflow/python/framework/dtypes.py", line 717, in as_dtype
    (type_value,))
TypeError: Cannot convert value 0 to a TensorFlow DType.
