### ISSUE TITLE
 Hi I have tensorrt 7.0.0 , I want to implement yolov2 and yolov3 darknet  on the same with T4. 

### ISSUE THREAD

**Issue by Abrahamma97** [jkjung-avt/tensorrt_demos#170]
Hi I have tensorrt 7.0.0 , I want to implement yolov2 and yolov3 darknet on the same with T4.

**Comment by jkjung-avt** [comment]
yolov3 is already supported.  Please follow the instructions in the README.

yolov2 might require some code changes.  You need to handle that by yourself.

**Comment by Abrahamma97** [comment]
Hi I tried but I couldnot debug it... could you help?

**Comment by jkjung-avt** [comment]
I suggest you to try yolov4 instead.  yolov4 is better, and it is already supported by this repo.

**Comment by Abrahamma97** [comment]
Actually I wanted to benchmark YoloV2 itself that was why ib both x86 and tensorrt

**Comment by jkjung-avt** [comment]
I don't plan to work on that myself.  I think the required code change is not much.  A reasonably skilled engineer should be able to make it work.

**Comment by Abrahamma97** [comment]
Can you tell me what all changes have to be done for the same. Sorry I am kinda new to this that is why?

**Comment by jkjung-avt** [comment]
I already told you that I'm not going to do that.  Please do not ask it repeatedly.

**Comment by Abrahamma97** [comment]
Ok thanks anyways for the quick response :+1:
