### ISSUE TITLE
Why does my inference TRT take so long？

### ISSUE THREAD

**Issue by honghande** [jkjung-avt/tensorrt_demos#172]
The following is my reasoning result, using tensor rt 6.0.15 + onnx1.4.1:
![image](https://user-images.githubusercontent.com/29244715/89097252-e6343300-d40f-11ea-97f9-2807928f81d0.png)

**Comment by jkjung-avt** [comment]
Which model are you testing??   yolov4 or yolov3?  608 or 416 or 288?  Why do you think it's too slow (comapring to what)?

**Comment by honghande** [comment]
@jkjung-avtYolov3，608, the upper left corner of the above figure shows that FPS 42.99 is not the detection time

**Comment by jkjung-avt** [comment]
The number looked OK to me.  Why do you think it "takes so long"?

**Comment by honghande** [comment]
@jkjung-avt Is FPS 42.99 the time to detect a picture?

**Comment by honghande** [comment]
Because I see that the image detected by yolov3 on your readme shows that the FPS is 3.07 and my detection is 42.99, so

**Comment by jkjung-avt** [comment]
FPS = frames per second.  "42.99 FPS" means that each frame is taking (1s / 42.99) = 23.26 milliseconds.  The time includes not only inference, but also image capture, preprocessing, postprocessing and display.

**Comment by honghande** [comment]
@jkjung-avt Thank you so much for your answers!
