### ISSUE TITLE
How to make batch inferences？

### ISSUE THREAD

**Issue by jiagh2010** [jkjung-avt/tensorrt_demos#175]
How to make batch inferences？ mtcnn？？ how to infer

**Comment by jkjung-avt** [comment]
Here's an outline of what needs to be changed.  It would actually require some significant code changes...

1. Adjust max_batch'es when building TensorRT engines:
    - https://github.com/jkjung-avt/tensorrt_demos/blob/a0cd57c62daf6fe1b08f120dc2bffe29f660d62d/mtcnn/create_engines.cpp#L197
    - https://github.com/jkjung-avt/tensorrt_demos/blob/a0cd57c62daf6fe1b08f120dc2bffe29f660d62d/mtcnn/create_engines.cpp#L207
    - https://github.com/jkjung-avt/tensorrt_demos/blob/a0cd57c62daf6fe1b08f120dc2bffe29f660d62d/mtcnn/create_engines.cpp#L217

2. In [TrtPNet.detect()](https://github.com/jkjung-avt/tensorrt_demos/blob/a0cd57c62daf6fe1b08f120dc2bffe29f660d62d/utils/mtcnn.py#L244), preprocess multiple images and stack them into a batch for inference.

3. Split output of the TensorRT engine for individual input images, and post-process them accordingly.
