### ISSUE TITLE
Error in download script no yolov4-608.cfg

### ISSUE THREAD

**Issue by karolmajek** [jkjung-avt/tensorrt_demos#178]
In this line should be 608, not 416 (288,416,416 instead of 288,416,608)

https://github.com/jkjung-avt/tensorrt_demos/blob/a0cd57c62daf6fe1b08f120dc2bffe29f660d62d/yolo/download_yolov4.sh#L15

**Comment by jkjung-avt** [comment]
You are right.  Thanks for the catch.  I've updated the code.

**Comment by karolmajek** [comment]
No problem. Sorry for not submitting PR.
Thanks!
