### ISSUE TITLE
Why should the class be converted from YOLO to SSD, during evaluation on COCO dataset?

### ISSUE THREAD

**Issue by mvanlierBCG** [jkjung-avt/tensorrt_demos#188]
In https://github.com/jkjung-avt/tensorrt_demos/blob/master/eval_yolo.py

in fucntion generate_results() on line 75, 76 you convert the estimated classes from yolo to ssd:
```
cls = int(cls)
cls = cls if non_coco else yolo_cls_to_ssd[cls]
```
why is this needed?

**Comment by jkjung-avt** [comment]
The yolov3/yolov4 models output **80** classes, as defined in [yolo_classes.py](https://github.com/jkjung-avt/tensorrt_demos/blob/1156ad5f66b298d61cf8040721376c8f2904941b/utils/yolo_classes.py#L6).  But "pycocotools" (or the original annotations in the COCO dataset) is expecting **91** classes as defined in [ssd_classes.py](https://github.com/jkjung-avt/tensorrt_demos/blob/1156ad5f66b298d61cf8040721376c8f2904941b/utils/ssd_classes.py#L7).
