### ISSUE TITLE
“WARNING: Using an engine plan file across different models of devices .....”

### ISSUE THREAD

**Issue by krambriw** [jkjung-avt/tensorrt_demos#194]
I made a little mistake. My target is to operate the Jetson Nano headless, i.e. without any monitor attached. The thing is while I built everything I had a monitor attached. When I removed the monitor and run my scripts I got a warning:

“WARNING: Using an engine plan file across different models of devices is not recommended and is likely to affect 
performance or even cause errors.”

I have understood it is in my case pretty harmless since I do not use different models of devices. Anyway it is annoying. So I decided to try to rebuild (from YOLOv4 demo nbr 5 step2. "python3 yolo_to_onnx.py --model yolov4-tiny-416" and optimization nbr 6), this time without monitor attached, just using vnc. This helped, the warning is gone

I just wonder if I did too much? Could it have been solved easier? Anyway maybe good to know if anyone would run into the same issue

Best regards, Walter

EDIT: I think it is enough to rebuild the engine, I tried to just rebuild the opt version in this way and it worked, no more warnings (deleted first the existing "libyolo_layer.so")

```
cd plugins
make
cd ..
cd yolo
python3 onnx_to_tensorrt.py --with_plugins --model yolov4-tiny-opt-416


```

**Comment by jkjung-avt** [comment]
Yes, you only need to rebuild the TensorRT engine.

I have not idea about this warning, though.  I have not tried to run the code headless, neither have I seen such an error on my Jetsons.

“WARNING: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.”
