### ISSUE TITLE
jetpack-4.4 for jetson tx2 :run     sudo python3 trt_mtcnn.py --xxx  error

### ISSUE THREAD

**Issue by fyyxxm** [jkjung-avt/tensorrt_demos#201]
AttributeError: 'Camera' object has no attribute 'open'

![jetson-mtcnn](https://user-images.githubusercontent.com/50574073/90950464-3db04680-e484-11ea-996e-bfdd7565a7e0.png)

**Comment by fyyxxm** [comment]
HI, 
After my test, GoogleNet can run normally. But MTCNN failed to run, and the error message is as shown in the figure above. The version is already up to date

**Comment by jkjung-avt** [comment]
This is indeed an oversight on my part.  I forgot to update "trt_mtcnn.py".

Thanks for reporting this issue.  I have fixed the code now.
