### ISSUE TITLE
conver yolo to onnx stop at building onnx gragh

### ISSUE THREAD

**Issue by momandai** [jkjung-avt/tensorrt_demos#208]
i run
```
python yolo_to_onnx.py -m yolov4-416
```
and it stop at building onnx graph, and memory is increasing
![image](https://user-images.githubusercontent.com/24688004/91406140-b3e1ee00-e874-11ea-8e6b-0dcf4bacf0d4.png)

**Comment by jkjung-avt** [comment]
I have never encountered such a problem.  Are you running this on a Jetson Nano?  Are you converting the pre-trained (downloaded) yolov4 model?

**Comment by momandai** [comment]
> I have never encountered such a problem. Are you running this on a Jetson Nano? Are you converting the pre-trained (downloaded) yolov4 model?

i ran this on Jetson TX2, jetpack4.3
i installed protobuf3.8.0 https://github.com/jkjung-avt/jetson_nano/blob/master/install_protobuf-3.8.0.sh
installed   onnx 1.4.1
ran
```
./download_yolo.sh
```
but when i convert pre-trained model
```
python3 yolo_to_onnx.py -m yolov4-416
```
it stucked at building onnx graph

**Comment by momandai** [comment]
it took about 8 minute to finish building onnx model, and   used 30% memory while converting to onnx, is it normal?
![image](https://user-images.githubusercontent.com/24688004/91522770-a3417e80-e92d-11ea-88f3-bf91234e06ef.png)

**Comment by jkjung-avt** [comment]
As long as the program does not throw an error or exception, I think it's OK.  I have tested my tensorrt yolo code on both Jetson Nano and Xavier NX, but not TX2 yet.  I think it'd work anyway.

**Comment by momandai** [comment]
thx, i tested yolov3-416.trt on TX2,  about 5.5 FPS
