### ISSUE TITLE
tensorrt_demos/utils/yolo_with_plugins.py RuntimeWarning: overflow encountered in exp

### ISSUE THREAD

**Issue by mvanlierBCG** [jkjung-avt/tensorrt_demos#212]
With the default yolov4, with input shape: 416x416 (as converted with your tools, I got the following overflow warning:

tensorrt_demos/utils/yolo_with_plugins.py
RuntimeWarning: overflow encountered in exp
  return np.reciprocal(np.exp(-array) + 1.0)

**Comment by jkjung-avt** [comment]
Please `git pull` the latest code.  The calculation you mentioned has already been moved to the yolo_layer CUDA kernel.  You should not encounter this problem with the latest code.

> tensorrt_demos/utils/yolo_with_plugins.py
RuntimeWarning: overflow encountered in exp
return np.reciprocal(np.exp(-array) + 1.0)
