### ISSUE TITLE
Demo on GTX 1080 Ti

### ISSUE THREAD

**Issue by MuhammadAsadJaved** [jkjung-avt/tensorrt_demos#215]
Hi, 
     I am using Geforce GTX 1080Ti GPU, I have installed TensorRT-5.0.2.6 and converted yolov3.weights to yolov3.trt.   Now I want to run the demo using this converted yolov3.trt model.  Can I use this project for the demo in GTX 1080Ti ? If no then how I can use this trt model for the interface in this GPU?

**Comment by jkjung-avt** [comment]
As stated in README.md,

> Demo #4 and Demo #5: requires TensorRT 6.x+.

If you upgrade your TensorRT library to TensorRT 6 or 7, the code should work on your GTX 1080 Ti.

**Comment by MuhammadAsadJaved** [comment]
@jkjung-avt OK. Thank you so much sir.
