### ISSUE TITLE
how to load more trt model

### ISSUE THREAD

**Issue by JF-Lee** [jkjung-avt/tensorrt_demos#219]
Thanks for your working! I have successfully run my yolov4-tiny trt model on NX, but when I want to load 2 models, an error occurred as
follows:

[TensorRT] ERROR: ../rtSafe/cuda/caskConvolutionRunner.cpp (491) - Cuda Error in execute: 400 (invalid resource handle)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception

I hope to get your answer, thank you!!!

**Comment by jkjung-avt** [comment]
If you are writing single-threaded code, just instantiate 2 TrtYOLO objects.  It should work.

In case you are creating multiple threads, you'll have to create/manage CUDA context for each thread.  You could refer to [trt_ssd_async.py](https://github.com/jkjung-avt/tensorrt_demos/blob/master/trt_ssd_async.py).

**Comment by JF-Lee** [comment]
Thanks for your reply, I have tried to instantiate 2 TrtYOLO objects with&nbsp;single-threaded, however It didn't work.
Code and error message are shown in the file.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jkjung-avt/tensorrt_demos"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 中午11:03
收件人:&nbsp;"jkjung-avt/tensorrt_demos"<tensorrt_demos@noreply.github.com&gt;;
抄送:&nbsp;"走走停停ゝ"<445099619@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jkjung-avt/tensorrt_demos] how to load more trt model (#219)





 
If you are writing single-threaded code, just instantiate 2 TrtYOLO objects.  It should work.
 
In case you are creating multiple threads, you'll have to create/manage CUDA context for each thread.  You could refer to trt_ssd_async.py.

**Comment by jkjung-avt** [comment]
> Code and error message are shown in the file.

Where is the file?

**Comment by JF-Lee** [comment]
The file was sent as an attachment, and the content of the file is as follows.


#########################
"""trt_yolo.py
This script demonstrates how to do real-time object detection with
TensorRT optimized YOLO engine.
"""

import os
import time
import argparse
import numpy as np
import cv2
import pycuda.autoinit&nbsp; # This is needed for initializing CUDA driver
from utils.yolo_classes import get_cls_dict
from utils.yolo import TrtYOLO
from utils.camera import add_camera_args, Camera
from utils.display import open_window, set_display, show_fps
from utils.visualization import BBoxVisualization

coco_cls_num = 80
road_cls_num = 1
coco_model = 'yolov4-tiny-416-coco'
road_model = 'yolov4-tiny-416-road'
cap = cv2.VideoCapture('/home/nx/LJF/video/sign.mp4')

if __name__ == '__main__':
&nbsp;&nbsp;&nbsp; coco_trt = TrtYOLO(coco_model, (416, 416), coco_cls_num)
&nbsp;&nbsp;&nbsp; road_trt = TrtYOLO(road_model, (416, 416), road_cls_num)
&nbsp;&nbsp;&nbsp; tic = time.time()
&nbsp;&nbsp;&nbsp; vid_writer = None
&nbsp;&nbsp;&nbsp; f_count = 0
&nbsp;&nbsp;&nbsp; while True:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; ret, frame = cap.read()
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; if frame is None:
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; continue
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; coco_boxes, coco_confs, coco_clss = coco_trt.detect(frame)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; road_boxes, road_confs, road_clss = road_trt.detect(frame)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; print(f_count)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; f_count += 1
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; cv2.waitKey(1)
&nbsp;&nbsp;&nbsp; cap.release()


#########################







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jkjung-avt/tensorrt_demos"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月8日(星期二) 晚上8:25
收件人:&nbsp;"jkjung-avt/tensorrt_demos"<tensorrt_demos@noreply.github.com&gt;;
抄送:&nbsp;"走走停停ゝ"<445099619@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jkjung-avt/tensorrt_demos] how to load more trt model (#219)





  
Code and error message are shown in the file.
  
Where is the file?

**Comment by jkjung-avt** [comment]
The following sample code works.  It demonstrates running 2 TrtYOLO detectors in one process.

```
import cv2
import pycuda.autoinit

from utils.yolo_with_plugins import TrtYOLO

img = cv2.imread('dog.jpg')
trt_yolo1= TrtYOLO('yolov4-416', (416, 416), 80)
trt_yolo2= TrtYOLO('yolov4-tiny-288', (288, 288), 80)
print(trt_yolo1.detect(img))
print(trt_yolo2.detect(img))
```

**Comment by JF-Lee** [comment]
Thanks for your great work, I have successfully deployed mult trt models with single-thread and mult-thread.Thanks again!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "jkjung-avt/tensorrt_demos"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年9月20日(星期天) 上午9:18
收件人:&nbsp;"jkjung-avt/tensorrt_demos"<tensorrt_demos@noreply.github.com&gt;;
抄送:&nbsp;"走走停停ゝ"<445099619@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [jkjung-avt/tensorrt_demos] how to load more trt model (#219)





 
The following sample code works.  It demonstrates running 2 TrtYOLO detectors in one process.
 import cv2 import pycuda.autoinit from utils.yolo_with_plugins import TrtYOLO img = cv2.imread('dog.jpg') trt_yolo1= TrtYOLO('yolov4-416', (416, 416), 80) trt_yolo2= TrtYOLO('yolov4-tiny-288', (288, 288), 80) print(trt_yolo1.detect(img)) print(trt_yolo2.detect(img))
