### ISSUE TITLE
about yolov3 and yolov4->onnx->trt

### ISSUE THREAD

**Issue by bamboosdu** [jkjung-avt/tensorrt_demos#224]
Hi, thanks for your wonderful work, and I have a question that whether the code for turning yolov3(darknet or pytorch) to trt is same with the code for turning yolov4(darknet or pytorch) or not.
If not, what is the difference？Looking forward to your reply！

**Comment by jkjung-avt** [comment]
Yes.

The code in this repo can be used to convert darknet yolo models (cfg/weights) into onnx models and TensorRT engines.  Pytorch is not supported.  The code is exactly the same for yolov3 and yolov4 models.

**Comment by bamboosdu** [comment]
> Yes.
> 
> The code in this repo can be used to convert darknet yolo models (cfg/weights) into onnx models and TensorRT engines. Pytorch is not supported. The code is exactly the same for yolov3 and yolov4 models.

Thanks a  lot for  your kind reply!
