### ISSUE TITLE
Restatr

### ISSUE THREAD

**Issue by PatrikPatrik2** [jkjung-avt/tensorrt_demos#228]
I have some times erroros in my rtsp feed, which results in that the program freezes (I have adresses this previously).

To get some input on solving this problem I wanted to restart trt_ssd after the "esc" key was pressed by running the code again (with a 30 second pause):

`    args = parse_args()
    cam = Camera(args)
    cam.open()
    if not cam.is_opened:
        sys.exit('Failed to open camera!')

    cls_dict = get_cls_dict(args.model.split('_')[-1])
    trt_ssd = TrtSSD(args.model, INPUT_HW)

    cam.start()
    open_window(WINDOW_NAME, args.image_width, args.image_height,
                'Camera TensorRT SSD Demo for Jetson Nano')
    vis = BBoxVisualization(cls_dict)
    loop_and_detect(cam, trt_ssd, conf_th=0.3, vis=vis)

    cam.stop()
    cam.release()
    cv2.destroyAllWindows()

    print("30 second pause start")
    time.sleep(30)
    print("Pause Ended")
    cam = Camera(args)
    cam.open()
    if not cam.is_opened:
        sys.exit('Failed to open camera!')

    cls_dict = get_cls_dict(args.model.split('_')[-1])
    trt_ssd = TrtSSD(args.model, INPUT_HW)

    cam.start()
    open_window(WINDOW_NAME, args.image_width, args.image_height,
                'Camera TensorRT SSD Demo for Jetson Nano')
    vis = BBoxVisualization(cls_dict)
    loop_and_detect(cam, trt_ssd, conf_th=0.3, vis=vis)`

this was  not sucessful, I got #assertiongridAnchorPlugin.cpp,205
Aborted (core dumped), see below

Do you know how I can get pass this error?

`2020-09-13 21:41:46.370477: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.2

(python3:11019): GStreamer-CRITICAL **: 21:41:50.056: gst_caps_is_empty: assertion 'GST_IS_CAPS (caps)' failed

(python3:11019): GStreamer-CRITICAL **: 21:41:50.056: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

(python3:11019): GStreamer-CRITICAL **: 21:41:50.056: gst_caps_fixate: assertion 'GST_IS_CAPS (caps)' failed

(python3:11019): GStreamer-CRITICAL **: 21:41:50.056: gst_caps_get_structure: assertion 'GST_IS_CAPS (caps)' failed

(python3:11019): GStreamer-CRITICAL **: 21:41:50.056: gst_structure_get_string: assertion 'structure != NULL' failed

(python3:11019): GStreamer-CRITICAL **: 21:41:50.056: gst_mini_object_unref: assertion 'mini_object != NULL' failed
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
Allocating new output: 1920x1088 (x 11), ThumbnailMode = 0
OPENMAX: HandleNewStreamFormat: 3605: Send OMX_EventPortSettingsChanged: nFrameWidth = 1920, nFrameHeight = 1080 
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (896) open OpenCV | GStreamer warning: unable to query duration of stream
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=1, value=0, duration=-1
30 second pause start
Pause Ended

(python3:11019): GStreamer-CRITICAL **: 21:42:47.389: gst_caps_is_empty: assertion 'GST_IS_CAPS (caps)' failed

(python3:11019): GStreamer-CRITICAL **: 21:42:47.390: gst_caps_truncate: assertion 'GST_IS_CAPS (caps)' failed

(python3:11019): GStreamer-CRITICAL **: 21:42:47.390: gst_caps_fixate: assertion 'GST_IS_CAPS (caps)' failed

(python3:11019): GStreamer-CRITICAL **: 21:42:47.390: gst_caps_get_structure: assertion 'GST_IS_CAPS (caps)' failed

(python3:11019): GStreamer-CRITICAL **: 21:42:47.390: gst_structure_get_string: assertion 'structure != NULL' failed

(python3:11019): GStreamer-CRITICAL **: 21:42:47.390: gst_mini_object_unref: assertion 'mini_object != NULL' failed
NvMMLiteOpen : Block : BlockType = 261 
NVMEDIA: Reading vendor.tegra.display-size : status: 6 
NvMMLiteBlockCreate : Block : BlockType = 261 
Allocating new output: 1920x1088 (x 11), ThumbnailMode = 0
OPENMAX: HandleNewStreamFormat: 3605: Send OMX_EventPortSettingsChanged: nFrameWidth = 1920, nFrameHeight = 1080 
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (896) open OpenCV | GStreamer warning: unable to query duration of stream
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=1, value=0, duration=-1
#assertiongridAnchorPlugin.cpp,205
Aborted (core dumped)`

**Comment by jkjung-avt** [comment]
No idea.  But I think you could reuse the "trt_ssd" object.  You don't need to instantiate a new one after the 30-sec sleep.
