### ISSUE TITLE
Plugin for x86_64

### ISSUE THREAD

**Issue by Sayyam-Jain** [jkjung-avt/tensorrt_demos#230]
Hi, thank you for the great work.
I've installed TensorRT following the Nvidia Documentation (Deb file).
Unfortunately, /usr/local/TensorRT doesn't exist.

Only /usr/src/tensorrt/ exists and it doesn't have lib and include folder. 
Can you please help. 
Thanks

**Comment by jkjung-avt** [comment]
Please replace [these 2 lines](https://github.com/jkjung-avt/tensorrt_demos/blob/1b274b874b59c0c7ed05f5efb2d89c0089fa3a15/plugins/Makefile#L30) in Makefile with:

```
TENSORRT_INCS=-I"/usr/include/x86_64-linux-gnu"
TENSORRT_LIBS=-L"/usr/lib/x86_64-linux-gnu"
```

**Comment by Sayyam-Jain** [comment]
Thank you. It worked
