### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by survAI-Tech** [jkjung-avt/tensorrt_demos#232]
I've followed all the steps in your blog jetpack-4.4 for jetson nano, but while compiling any of the project I'm getting following error.

desktop:~/AMS/tensorrt_demos/mtcnn$ make
../common/Makefile.config:4: CUDA_INSTALL_DIR variable is not specified, using /usr/local/cuda by default, use CUDA_INSTALL_DIR=<cuda_directory> to change.
../common/Makefile.config:7: CUDNN_INSTALL_DIR variable is not specified, using  by default, use CUDNN_INSTALL_DIR=<cudnn_directory> to change.
:
Compiling: create_engines.cpp
create_engines.cpp: In function ‘void caffeToTRTModel(const string&, const string&, const std::vector<std::__cxx11::basic_string<char> >&, unsigned int, nvinfer1::IHostMemory*&)’:
create_engines.cpp:81:58: warning: ‘virtual nvinfer1::INetworkDefinition* nvinfer1::IBuilder::createNetwork()’ is deprecated [-Wdeprecated-declarations]
     INetworkDefinition* network = builder->createNetwork();
                                                          ^
In file included from create_engines.cpp:29:0:
/usr/include/aarch64-linux-gnu/NvInfer.h:6799:58: note: declared here
     TRT_DEPRECATED virtual nvinfer1::INetworkDefinition* createNetwork() TRTNOEXCEPT = 0;
                                                          ^~~~~~~~~~~~~
create_engines.cpp:103:42: warning: ‘virtual void nvinfer1::IBuilder::setMaxWorkspaceSize(std::size_t)’ is deprecated [-Wdeprecated-declarations]
     builder->setMaxWorkspaceSize(64 << 20);
                                          ^
In file included from create_engines.cpp:29:0:
/usr/include/aarch64-linux-gnu/NvInfer.h:6830:33: note: declared here
     TRT_DEPRECATED virtual void setMaxWorkspaceSize(std::size_t workspaceSize) TRTNOEXCEPT = 0;
                                 ^~~~~~~~~~~~~~~~~~~
create_engines.cpp:110:34: warning: ‘virtual void nvinfer1::IBuilder::setFp16Mode(bool)’ is deprecated [-Wdeprecated-declarations]
         builder->setFp16Mode(true);
                                  ^
In file included from create_engines.cpp:29:0:
/usr/include/aarch64-linux-gnu/NvInfer.h:7127:33: note: declared here
     TRT_DEPRECATED virtual void setFp16Mode(bool mode) TRTNOEXCEPT = 0;
                                 ^~~~~~~~~~~
create_engines.cpp:114:60: warning: ‘virtual nvinfer1::ICudaEngine* nvinfer1::IBuilder::buildCudaEngine(nvinfer1::INetworkDefinition&)’ is deprecated [-Wdeprecated-declarations]
     ICudaEngine* engine = builder->buildCudaEngine(*network);
                                                            ^
In file included from create_engines.cpp:29:0:
/usr/include/aarch64-linux-gnu/NvInfer.h:6934:51: note: declared here
     TRT_DEPRECATED virtual nvinfer1::ICudaEngine* buildCudaEngine(
                                                   ^~~~~~~~~~~~~~~
Linking: create_engines

Please help me out how to dubug this.

**Comment by jkjung-avt** [comment]
Those are all just warnings that could be ignored.

You could execute "create_engines" to build the TensorRT engines.
