### ISSUE TITLE
How can I use YOLO custom model?

### ISSUE THREAD

**Issue by Rain3321** [jkjung-avt/tensorrt_demos#233]
I made my custom model with darknet, and I want to change darknet to tensorRT.
I used my custom pill weights, yolo-pill-416.weights, but when I run the tensorRT, the detecting name is not my data, it is coco.data
how can I change the data?

**Comment by jkjung-avt** [comment]
You could define your own "cls_dict" in the source code.  Refer to: https://github.com/jkjung-avt/tensorrt_demos/blob/ecedc327fbf28eaa081c4cbf3773020e5b79005e/trt_yolo.py#L91

For example, you could replace that line with:

```
    cls_dict = { 0: 'foo', 1: 'bar', 2: 'baz' }
```
