### ISSUE TITLE
does trt file platform dependent?

### ISSUE THREAD

**Issue by taka-wang** [jkjung-avt/tensorrt_demos#234]
Thanks for your great efforts. Currently, I follow your demo5 to convert model from yolo to onnx then TRT. However, the trt file looks like platform dependent (x86, nano, nx). Is it true?

**Comment by jkjung-avt** [comment]
Yes.  You need to build the TensorRT engine on your "target" platform.  A TensorRT engine built on x86_64 could not be used on Jetson Nano.

**Comment by taka-wang** [comment]
Thanks 🙏
