### ISSUE TITLE
I wonder pretrained model  YOLO

### ISSUE THREAD

**Issue by hjlee9182** [jkjung-avt/tensorrt_demos#235]
When I install using ./download_yolo.sh , I have yolo weight.

Is weight trained all COCO training set? ( 90 class)

**Comment by jkjung-avt** [comment]
Yes, the downloaded yolo models were trained with COCO dataset.  It outputs **80 classes**.  You could refer to this file: [darknet/data/coco.names](https://github.com/AlexeyAB/darknet/blob/master/data/coco.names)

**Comment by hjlee9182** [comment]
Thank you!!!!
