### ISSUE TITLE
Makefile error 

### ISSUE THREAD

**Issue by CODEDISON** [jkjung-avt/tensorrt_demos#241]
Mine is 1080Ti and I have already correctly set the CUDA compute("compute = 61").But it still raises "Makefile:20: "compute=75" is for GeForce RTX-2080 Ti.  Please make sure CUDA compute is set correctly for your system in the Makefile."
what should I do?

**Comment by jkjung-avt** [comment]
That is due to the following warning in the Makefile.  If you are sure you've set "compute" correctly for your GPU, you could ignore (or remove) the warning.

https://github.com/jkjung-avt/tensorrt_demos/blob/96bcfeb9184bbd0c152685db2565259aa62e9871/plugins/Makefile#L20
