### ISSUE TITLE
What does “--model” mean？

### ISSUE THREAD

**Issue by jch-wang** [jkjung-avt/tensorrt_demos#242]
Does  “yolov4-288” in model represent  “yolov4-288.weights” and “yolov4-288.cfg” under folder “yolov4-288”?

**Comment by jkjung-avt** [comment]
Yes.  In addition, "trt_yolo.py" will look for "yolov4-288.trt" (serialized TensorRT engine) in the "yolo/" directory.

**Comment by jch-wang** [comment]
> Yes. In addition, "trt_yolo.py" will look for "yolov4-288.trt" (serialized TensorRT engine) in the "yolo/" directory.

Thank you very much for your prompt reply. I think I understand what you mean.
