### ISSUE TITLE
How to create TRT engines of yoloV3-608 with different batch sizes

### ISSUE THREAD

**Issue by Abrahamma97** [jkjung-avt/tensorrt_demos#249]
Hi ,
I want to create TRT engines of yoloV3-608 with different batch sizes with INT8 and fp16 precision.Should I only change  
64 -MAX_BATCH_SIZE = 1
64+MAX_BATCH_SIZE = 128 for 128 batch size or similar batch sizes.

**Comment by jkjung-avt** [comment]
I haven't tested my TensorRT YOLO code with batch size larger than 1.  But I think it's straight forward to modify my "onnx_to_tensorrt.py" to build TensorRT engines with larger batch sizes.

* For TensorRT 6: just set `builder.max_batch_size` to your targeted max batch size.

   https://github.com/jkjung-avt/tensorrt_demos/blob/2c37329c4aae9409d1db907a77eb97d581c75610/yolo/onnx_to_tensorrt.py#L120

* For TensorRT 7: specify [optimization profiles](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#opt_profiles).  (Please refer to official TensorRT documentation for explanations.)

   https://github.com/jkjung-avt/tensorrt_demos/blob/2c37329c4aae9409d1db907a77eb97d581c75610/yolo/onnx_to_tensorrt.py#L136-L140

Please note that the inference code need to be modified to handle batched output as well.

https://github.com/jkjung-avt/tensorrt_demos/blob/master/utils/yolo_with_plugins.py#L288
