### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by xpeedster** [jkjung-avt/tensorrt_demos#254]
Hi again,

One question. How should I reference your work if I'm using it on a thesis?

Thanks in advance.

**Comment by jkjung-avt** [comment]
Ha.  This is the 1st time I get such a question.  I think it's good enough if you use an URL to my GitHub repository or my blog post.  I'm happy if you mention my name as well.

Thanks for the inquiry.

**Comment by xpeedster** [comment]
Okay, thanks for the information. I will do as you say
