### ISSUE TITLE
Issue regrading size and type of the model during conversion from ONNX to TRT

### ISSUE THREAD

**Issue by Darshcg** [jkjung-avt/tensorrt_demos#258]
Hi @jkjung-avt,

I am trying to convert our Custom model from ONNX to tensorrt Model in Jetson Nano. The conversion is happening without errors, but after the Conversion the size and type of the TRT Model being generated in Jetson Nano are completely different when I am converting in my Local System.

-> Size of the ONNX Model= 251 MB
->Size of the TRT Model being generated in Jetson Nano= 605 MB[Type: STL 3D Model(binary)]
-> Size of the TRT model being generated in my Local System= 250MB[Type: binary]

What is the reason behind the same and how to avoid this?

The below attached image describes the Information of the TRT Model being generated in Jetson Nano.
![image](https://user-images.githubusercontent.com/48723743/95750714-2c80fa80-0cbb-11eb-98d0-2e4f72913039.png)

**Comment by jkjung-avt** [comment]
I'm not able to answer this question.  Please follow up with NVIDIA directly: https://github.com/NVIDIA/TensorRT/issues/820.
