### ISSUE TITLE
How to get this map?

### ISSUE THREAD

**Issue by hjlee9182** [jkjung-avt/tensorrt_demos#264]
![image](https://user-images.githubusercontent.com/46337218/96393320-ba983c00-11f9-11eb-8aca-023a9d3f12ea.png)

![image](https://user-images.githubusercontent.com/46337218/96393339-c5eb6780-11f9-11eb-95ea-16744cd9dca2.png)

In yolov4 paper, yolov4 map is almost 44.

But you got over 70. How to get that point?
And What is difference between this result and paper?

**Comment by jkjung-avt** [comment]
Thanks for asking.

According to the original [YOLOv4 paper](https://arxiv.org/pdf/2004.10934.pdf), AP and AP_50 of "yolov4-608" are **43.5%** and **65.7%** respectively.  You could refer to my [Verifying mAP of TensorRT Optimized SSD and YOLOv3 Models](https://jkjung-avt.github.io/trt-detection-map/) post for a better understanding about AP (mAP @ IoU=0.5:0.95) and AP_50 (mAP @ IoU=0.5).

![mAP](https://user-images.githubusercontent.com/19985967/96394610-072d4880-11f5-11eb-9388-61d2a0d47ea1.jpg)

In contrast, when I used my own [eval_yolo.py](https://github.com/jkjung-avt/tensorrt_demos/blob/master/eval_yolo.py) to verify mAP of my TensorRT yolov4-608 (FP16) engine, I got **0.488** and **0.736**.  Those numbers were slightly higher than what's in the original paper.

I myself am not 100% sure why.  But I think it might be related to how non-maximum suppression (NMS) should have been done when I evaluate mAP of the engines.

**Comment by hjlee9182** [comment]
ok thanks!! :)
