### ISSUE TITLE
failure to compile plugins

### ISSUE THREAD

**Issue by Yaoxingtian** [jkjung-avt/tensorrt_demos#273]
Hi, when I make plugins , here come up with soem errors as below. Does anybody know what's the problems , I use 1080ti,py3.
thanks a lot !

errors:
...
yolo_layer.cu(151): error: identifier "PluginTensorDesc" is undefined

yolo_layer.cu(151): error: identifier "PluginTensorDesc" is undefined

yolo_layer.cu(181): error: identifier "IPluginV2IOExt" is undefined

**Comment by jkjung-avt** [comment]
https://github.com/jkjung-avt/tensorrt_demos/blob/e039e0824876d46443aa19e9ad7cf8f7723c713e/plugins/Makefile#L30-L31

Please modify these paths to point to where your TensorRT include files and library files could be located.

**Comment by jkjung-avt** [comment]
Closing this since there's no further question.
