### ISSUE TITLE
demo5 yolov4 has no result  QAQ, anyone help me out?

### ISSUE THREAD

**Issue by hellosummer8850** [jkjung-avt/tensorrt_demos#275]
Hi, I just wana try the demo5 Yolov4 trt to infer a single dog.jpg with trt_yolo.py,  as I followed all the steps and it seems that a trt engine is well generated, by when I try to run it, it just showed a graph but without bbx drawing, my tensorRT is with version 7.1.3.4 and cudnn 8 + cuda 11, can anyone help me out?

**Comment by hellosummer8850** [comment]
my yolo folder is like this:
![image](https://user-images.githubusercontent.com/18628964/97680780-3768c700-1ad2-11eb-94b0-32f9c50692b0.png)
but no drawing of bbx like this:
![image](https://user-images.githubusercontent.com/18628964/97680854-4fd8e180-1ad2-11eb-937d-3bf37576ec42.png)

**Comment by jkjung-avt** [comment]
https://github.com/jkjung-avt/tensorrt_demos/issues/261#issuecomment-720032042
