### ISSUE TITLE
How to run yolo sample using multithreading ?

### ISSUE THREAD

**Issue by LK007CX** [jkjung-avt/tensorrt_demos#276]
It will run  well when I run `python3 trt_yolo.py --usb 0 -m yolov4-tiny-416` in command line.
But when I try to rewrite the *trt_yolo.py* with threading.thread, an error will occur.
 Here is the code I've rewritten.
How to run yolo sample using multithreading  corrently?
I hope your answer.
Your sincerely.

```python
import numpy as np
import argparse
from threading import Thread

import pycuda.autoinit  # This is needed for initializing CUDA driver

from utils.yolo_classes import get_cls_dict
from utils.camera import add_camera_args, Camera
from utils.display import open_window, set_display, show_fps
from utils.visualization import BBoxVisualization
from utils.yolo_with_plugins import TrtYOLO


WINDOW_NAME = 'TrtYOLODemo'


class DetectTensorRT(Thread):

    def __init__(self, args, parent=None):
        super(DetectTensorRT, self).__init__(parent)
        # Thread.__init__(self)
        self.args = args
        self.cam = None
        self.trt_yolo = None
        self.conf_th = 0.3
        self.vis = None
        
    
    def load_tensorRT(self):
        if self.args.category_num <= 0:
            raise SystemExit('ERROR: bad category_num (%d)!' % self.args.category_num)
        if not os.path.isfile('yolo/%s.trt' % self.args.model):
            raise SystemExit('ERROR: file (yolo/%s.trt) not found!' % self.args.model)

        self.cam = Camera(self.args)
        if not self.cam.isOpened():
            raise SystemExit('ERROR: failed to open camera!')

        cls_dict = get_cls_dict(self.args.category_num)
        yolo_dim = self.args.model.split('-')[-1]
        if 'x' in yolo_dim:
            dim_split = yolo_dim.split('x')
            if len(dim_split) != 2:
                raise SystemExit('ERROR: bad yolo_dim (%s)!' % yolo_dim)
            w, h = int(dim_split[0]), int(dim_split[1])
        else:
            h = w = int(yolo_dim)
        if h % 32 != 0 or w % 32 != 0:
            raise SystemExit('ERROR: bad yolo_dim (%s)!' % yolo_dim)

        self.trt_yolo = TrtYOLO(self.args.model, (h, w), self.args.category_num)
        self.vis = BBoxVisualization(cls_dict)

    def loop_and_detect(self):
        full_scrn = False
        fps = 0.0
        tic = time.time()
        while True:
            if cv2.getWindowProperty(WINDOW_NAME, 0) < 0:
                break
            img = self.cam.read()
            if img is None:
                break
            boxes, confs, clss = self.trt_yolo.detect(img, self.conf_th)
            img = self.vis.draw_bboxes(img, boxes, confs, clss)
            img = show_fps(img, fps)
            cv2.imshow(WINDOW_NAME, img)
            # self.image_Signal.emit(img)
            toc = time.time()
            curr_fps = 1.0 / (toc - tic)
            # calculate an exponentially decaying average of fps number
            fps = curr_fps if fps == 0.0 else (fps*0.95 + curr_fps*0.05)
            tic = toc
            key = cv2.waitKey(1)
            if key == 27:  # ESC key: quit program
                break
            elif key == ord('F') or key == ord('f'):  # Toggle fullscreen
                full_scrn = not full_scrn
                set_display(WINDOW_NAME, full_scrn)

    def run(self):
        try:
            self.load_tensorRT()
            self.loop_and_detect()
        finally:
            self.cam.release()

class ArgsHelper:

    __slots__ = 'image', 'video', 'video_looping', 'rtsp', 'rtsp_latency', 'usb', 'onboard', 'copy_frame', 'do_resize', 'width', 'height', 'category_num', 'model'
    
    def __init__(self, *args, **kwargs):
        for k, v in kwargs.items():
            setattr(self, k, v)
         

if __name__ == "__main__":
    args = ArgsHelper(image=None, video=None, video_looping=False,rtsp=None, rtsp_latency=200, usb=0, onboard=None, copy_frame=False, do_resize=False, width=640, height=480, category_num=80, model='yolov4-tiny-416')
    thread1 = DetectTensorRT(args)
    thread1.start()
```
outputs is 
*edit@edit-desktop:~/code/Multichannel_Camera_Demo$ /usr/bin/python3 /home_Demo/Detect.pyichannel_Camera_
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (933) open OpenCV | GStreamer warning: Cannot query video position: status=0, value=-1, duration=-1
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/edit/code/Multichannel_Camera_Demo/utils/yolo_with_plugins.py", line 257, in __init__
    allocate_buffers(self.engine, grid_sizes)
  File "/home/edit/code/Multichannel_Camera_Demo/utils/yolo_with_plugins.py", line 153, in allocate_buffers
    stream = cuda.Stream()
pycuda._driver.LogicError: explicit_context_dependent failed: invalid device context - no currently active context?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/home/edit/code/Multichannel_Camera_Demo/Detect.py", line 93, in run
    self.load_tensorRT()
  File "/home/edit/code/Multichannel_Camera_Demo/Detect.py", line 61, in load_tensorRT
    self.trt_yolo = TrtYOLO(self.args.model, (h, w), self.args.category_num)
  File "/home/edit/code/Multichannel_Camera_Demo/utils/yolo_with_plugins.py", line 259, in __init__
    raise RuntimeError('fail to allocate CUDA resources') from e
RuntimeError: fail to allocate CUDA resources

Exception ignored in: <bound method TrtYOLO.__del__ of <utils.yolo_with_plugins.TrtYOLO object at 0x7f9917fcc0>>
Traceback (most recent call last):
  File "/home/edit/code/Multichannel_Camera_Demo/utils/yolo_with_plugins.py", line 266, in __del__
    del self.outputs
AttributeError: outputs*

**Comment by jkjung-avt** [comment]
Replace this line:

```
        self.trt_yolo = TrtYOLO(self.args.model, (h, w), self.args.category_num)
```

with this:

```
        self.trt_yolo = TrtYOLO(self.args.model, (h, w), self.args.category_num, cuda_ctx=pycuda.autoinit.context)
```

since you are doing TensorRT inferencing in a child thread.

**Comment by jkjung-avt** [comment]
I assume this issue has been resolved.
