### ISSUE TITLE
Request for a DeepSort demo

### ISSUE THREAD

**Issue by jamesee** [jkjung-avt/tensorrt_demos#279]
Hi jkjung

Thank you for the superb demos. I can now run Yolov4-tiny on tensorRT at more than 50fps on jetson nx.

May I request a deepsort demo using your plugin. Many thanks in advance.

James

**Comment by jkjung-avt** [comment]
@jamesee  Thanks for the suggestion.  But I don't have a plan to add DeepSort (or other trackers) into the demos in this repository.  I will consider it when I have the time and energy to create a new project.

**Comment by jamesee** [comment]
@jkjung-avt 

Noted with thanks.

**Comment by GeekAlexis** [comment]
@jamesee I think I have exactly what you want: https://github.com/GeekAlexis/FastMOT 
@jkjung-avt Thanks for your great repo

**Comment by jkjung-avt** [comment]
@GeekAlexis  Sounds good.  Thanks for sharing.

**Comment by jamesee** [comment]
> @jamesee Here is my implementation: https://github.com/GeekAlexis/FastMOT
> @jkjung-avt Thanks for your great repo

@GeekAlexis 
Thank you for the info and great repo. Will study in detail.
