### ISSUE TITLE
How to run     mtcnn.detect(img, minsize=minsize)    using a  child thread?

### ISSUE THREAD

**Issue by 17120033** [jkjung-avt/tensorrt_demos#280]
Hi @jkjung-avt,

now i need to do  mtcnn.detect()  in  the while loop  using a child thread, 
there comes CUDA context problem,
I refer to the solution of multithreading in trtyolo,  like #276,
but I find that trt_mtcnn and trt_yolo are not very similar. 
How should I solve this problem?
hope your answer!
Your sincerely!

**Comment by 17120033** [comment]
the cuda context was initialized in the main thread (mtcnn=TrtMtcnn(engine))  while the inference (mtcnn.detect()) was in a child thread.

**Comment by jkjung-avt** [comment]
Please post the exact error messages (as detailed as possible) you're seeing.  I think it could be a different problem.

**Comment by jkjung-avt** [comment]
Closing this due to no response.

**Comment by 17120033** [comment]
Sorry,  i forgot to tell you @jkjung-avt,  We have noticed that the error is due to our code, and thank you very much again for your excellent work！！！！！！！！！！！！！！

**Comment by jkjung-avt** [comment]
@17120033  Good to hear that.
