### ISSUE TITLE
yolov3 output is zero

### ISSUE THREAD

**Issue by Daniel-1597** [jkjung-avt/tensorrt_demos#281]
![Screenshot from 2020-11-12 12-53-05](https://user-images.githubusercontent.com/53418529/98908410-4bd89680-24b8-11eb-946d-b09c49bb0fad.png)
I have gone through issues but I couldn't find the reason please let me know what can be the issue.

Thanks, 
Daniel

**Comment by jkjung-avt** [comment]
Your issue description is too unspecific, so I cannot help much.

Are you running the code with the downloaded (pretrained with COCO) yolov3 model?

Otherwise, check out:

* https://github.com/jkjung-avt/tensorrt_demos/issues/275
* https://github.com/jkjung-avt/tensorrt_demos/issues/261

**Comment by Daniel-1597** [comment]
I have downloaded the weights from.sh file after that I have converted to onnx model and trt while I am doing inference the model is not detecting anything.

**Comment by Daniel-1597** [comment]
I am trying it on p2.8xlarge with cuda 10.0 and trt 6.0.1.5

**Comment by jkjung-avt** [comment]
Try updating the CUDA driver.

**Comment by Daniel-1597** [comment]
I will update and I will check it

**Comment by Daniel-1597** [comment]
Configuration on Jetson AGX
CUDA-10.2
TensorRT - 7.1.3.0

I have tried it on Jetson AGX it worked with coco weights... Now when I am trying with my own custom yolov3 model.. I am getting  an error 
**Weights are outside of the fp16 range. A possible fix is to retrain the model with regularization to bring the magnitude of the weights down.)
ERROR: Failed to build the TensorRT engine!**
Can you please tell me How to train the yolov3 model with FP16? I am unable to train I tried multiple methods. 
Thanks, 
Daniel

**Comment by jkjung-avt** [comment]
https://github.com/jkjung-avt/tensorrt_demos/issues/161#issuecomment-662473343

**Comment by Daniel-1597** [comment]
Ok thanks I have one more question regarding int8 conversion I am getting out of memory error.

**Comment by jkjung-avt** [comment]
Please refer to the FPS numbers I posted in the README (for Jetson Nano).  You would be able to achieve higher FPS if you code with C++ (or use DeepStream SDK).

Reference: https://github.com/AlexeyAB/darknet/pull/5453#issuecomment-663593512

**Comment by Daniel-1597** [comment]
One more question I trained my custom model by changing the weight decay still there is the same problem weights are out of fp16 range... can you suggest weight decay value or how to train the model so that weights will be in fp16

**Comment by jkjung-avt** [comment]
You could refer to my [yolov4_crowdhuman examples](https://github.com/jkjung-avt/yolov4_crowdhuman/tree/master/cfg).  In addition to that, I have also trained other custom models in a very similar way.  I always used `decay=0.0005` as set in the original [yolov4-custom.cfg](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4-custom.cfg) and [yolov4-tiny-custom.cfg](https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4-tiny-custom.cfg).  And the resulting model could be optimized as TensorRT FP16 engines without any problem.

I think 0.05 is too large.

**Comment by Daniel-1597** [comment]
yeah I will go through them if I have any doubt I will let you know. Thanks for your immediate replies :-)

**Comment by Daniel-1597** [comment]
I will attach my weight files and cfg can you try converting them into TRT

**Comment by jkjung-avt** [comment]
Please work on that by yourself.

**Comment by Daniel-1597** [comment]
sure
