### ISSUE TITLE
Failed_to_parse_cfg_file_Yolo_Custom

### ISSUE THREAD

**Issue by rodolfobetanzos** [jkjung-avt/tensorrt_demos#284]
Hi Kjung , first at all thanks for your work because sometimes when I thing that this is too dificult, your advices give me a kind of refresh.I want to learn more about TensorRT and I have a little issue with my custom model Yolov3 :

I have trained my custom model Yolov3 for 2 categories and I have obtained the .cfg and weight files however when I run "python3 yolo_to_onnx.py -m yolov3-custom-416x416 --category_num 2" I got he next error:

$ python3 yolo_to_onnx.py -m yolov3-custom-416 --category_num 2
Parsing DarkNet cfg file...
Traceback (most recent call last):
File "yolo_to_onnx.py", line 955, in <module>
main()
File "yolo_to_onnx.py", line 896, in main
layer_configs = parser.parse_cfg_file(cfg_file_path)
File "yolo_to_onnx.py", line 94, in parse_cfg_file
layer_dict, layer_name, remain der = self._next_layer(remainder)
File "yolo_to_onnx.py", line 150, in _next_layer
param_type, param_value = self._parse_params(param_line)
File "yolo_to_onnx.py", line 177, in _parse_params
param_value = float(param_value_raw)
ValueError: could not convert string to float: '21#(noofclass+5)*3'

Have attached the .cfg and weight files on the next link
https://we.tl/t-WMyCusBAau

Could you please give me a advise? 
Thanks in advanced.
Best regards.

**Comment by jkjung-avt** [comment]
"yolo_to_onnx.py" does not handle trailing comments correctly.  You could avoid the problem by simply replacing line 35 of your "yolov3-custom-416.cfg":

    ```
    filters=21  #(no of class+5)*3
    ```

with:

    ```
    filters=21
    ```
