### ISSUE TITLE
onnx_to_tensorrt.py error

### ISSUE THREAD

**Issue by khoer26** [jkjung-avt/tensorrt_demos#286]
Hi sir
when I run that script i get the error

python3: yolo_layer.cu:115: virtual nvinfer1::Dims nvinfer1::YoloLayerPlugin::getOutputDimensions(int, const nvinfer1::Dims*, int): Assertion `inputs[0].d[0] == (mNumClasses + 5) * mNumAnchors' failed.
Aborted

Can you help me to solve that error?
Thank you sir

**Comment by jkjung-avt** [comment]
https://github.com/jkjung-avt/tensorrt_demos/issues/278#issuecomment-722752995
