### ISSUE TITLE
TensorRT includes and libs

### ISSUE THREAD

**Issue by sgriset** [jkjung-avt/tensorrt_demos#287]
I compile the plugin code for yolo support.  I'm compiling on Xavier NX running jetpack 4.4.  The TensorRT includes and libraries are not in /usr/local.  Do you know where they are located in jetpack 4.4?

**Comment by jkjung-avt** [comment]
Check if you could find these files:

* /usr/include/aarch64-linux-gnu/NvInfer.h
* /usr/lib/aarch64-linux-gpu/libnvinfer.so

**Comment by sgriset** [comment]
Thank you!
