### ISSUE TITLE
dockerfile

### ISSUE THREAD

**Issue by alicera** [jkjung-avt/tensorrt_demos#290]
Do you have the dockerfile？

I cant install pycuda 

thanks you

**Comment by jkjung-avt** [comment]
I don't understand your question.  I tested the code in this repository on my Jetson Nano, Xavier NX and x86_64 PC.  I ran the code directly (without Docker).

**Comment by alicera** [comment]
ok , thank you.
Do you have try the yolov5 ？

**Comment by jkjung-avt** [comment]
> Do you have try the yolov5?

No, I have not tried yolov5.

**Comment by alicera** [comment]
Do you have any idea to generate calibration for yolov5？

**Comment by jkjung-avt** [comment]
The procedure should be similar to how we do it for yolov4 and yolov3.
