### ISSUE TITLE
Yolov3 Performance on Xavier Jetpack 4.2.2 TensorRT5

### ISSUE THREAD

**Issue by mbufi** [jkjung-avt/tensorrt_demos#30]
Hi Jk! 

What an update you made! Just wanted to let you know that there is no issues with the yolo models... I just want to give you some more numbers all tested on the Xavier. 

Yolo-288 (FP16) = ~31 FPS
Yolo-416 (FP16) = ~20 FPS 
Yolo-608 (FP16) = ~12 FPS 

Thank you for all your hard work and awesome documentation. 

Cheers :smile:

**Comment by jkjung-avt** [comment]
Thanks again for letting me know your test results on Jetson AGX Xavier.

**Comment by mehshankhan** [comment]
Please share GitHub repositories.
