### ISSUE TITLE
Possibility of adding Darknet Yolo-v2-tiny > ONNX conversion to yolo_to_onnx.py?

### ISSUE THREAD

**Issue by ROBYER1** [jkjung-avt/tensorrt_demos#302]
First off, just wanted to say the yolo_to_onnx.py script is INCREDIBLE! So simple to work with compared to other ways of conversion I found (namely converting from darknet-TF-frozenTF-ONNX which were horrible and long)

I just wanted to ask if you had any means of adding Yolo-v2-tiny conversion to the  yolo_to_onnx.py script?

Mainly asking as I am working with this repo for an AR project and it only uses Yolo-v2-tiny and when I went to use a Yolo-v3-tiny model, I realised that the parsing of inputs/outputs is quite different in Yolo-v2-tiny
https://github.com/derenlei/Unity_Detection2AR

**Comment by jkjung-avt** [comment]
I don' have a plan to update this repo for yolov2-tiny, although I think the required work is not much.  I'm working on something else and will probably update this repo soon.
