### ISSUE TITLE
yolov4-416 performance on Jetson Nano

### ISSUE THREAD

**Issue by aeozyalcin** [jkjung-avt/tensorrt_demos#310]
Hello @jkjung-avt!

Thank you so much for the work you have put into this repo. It has made deploying YOLO models with TRT on the Nano a breeze!

Looking closer into the YOLO demo with the yolov4-416 model and evaluating it on my Nano, I am getting similar performance to what you have here, about 4 FPS.

To see where the bottleneck is, I modified trt_yolo.py and sprinkled some simple time.process_time() statements within the loop_and_detect function to see how long some of the items were taking to execute. Mainly, I "profiled" the `boxes, confs, clss = trt_yolo.detect(img, conf_th)` line to see how long inference was taking to complete, and the results have me scratching my head...

Profiling done like this:
```        ...
        start = time.process_time()
        boxes, confs, clss = trt_yolo.detect(img, conf_th)
        end = time.process_time()
        ...
        ...
        print(1/(end-start), fps)
        ...
```

Numbers below are "reciprocal of time taken to execute `trt_yolo.detect()`" and "FPS calculated and printed on every frame", respectively.

```
...
...
41.5978793733876 3.6154976874815663
39.5154411130411 3.631870247803036
41.36797951259104 3.6530086324862934
40.434762655020414 3.672561741529713
31.869230095809893 3.6861914339073607
41.14661799076797 3.6871450944986393
41.52572317150789 3.707035533266596
42.4518616054032 3.723861565702247
40.99560281164417 3.708829917592903
41.040723807337294 3.729758568011903
41.09527454479052 3.750964356663242
40.790571863016154 3.7508688879824916
41.27745637086307 3.770836050891327
41.796554684920835 3.7845075375313026
41.62475227548938 3.8053936308875964
41.738223372453504 3.8115525241169466
30.658191516203697 3.829063882496564
41.91920191205224 3.833823870659002
41.848204176383476 3.8505821717944255
41.754743077848154 3.8310975423967264
41.6798722395233 3.8456613011986907
41.513602554583315 3.811521138095755
41.117180098265486 3.8296584569871452
...
...
```

^^ These numbers suggest that the actual inference (`trt_yolo.detect`) only takes about 25ms per frame, however for some reason it is taking the application ~250ms to read a frame, do inference, annotate, and cv2.imshow each frame. So I got to commenting things out trying to figure out where the bottleneck is. I commented out cv2.imshow, I commented out frame annotation, and I even changed the code so that the `loop_and_detect `keeps working on the same frame to eliminate decoding new frames.

What I found was.... well nothing really. Even with all these modifications, each iteration of the while loop with `loop_and_detect` is still taking ~250ms, but somehow I am lead to believe that the actual inferencing only takes 25ms! I am really confused by this, and I may have some false hope that we can somehow run yolov4-416 over 30fps.

P.S.: Your yolov4_crowdhuman repo/tutorial seems like it's a custom trained version of yolov4-416, rather than yolov4-tiny-416. And the modified Marvel trailer video you shared with your custom yolov4_crowdhuman detector shows 30+ FPS speed on a Jetson Nano. So does that actually mean that I should somehow be able to get 30+ FPS with yolov4-416 on my Jetson Nano?

Thanks in advance!

**Comment by jkjung-avt** [comment]
According to [python3 documentation](https://docs.python.org/3/library/time.html):

> time.**process_time()** → float
> Return the value (in fractional seconds) of the sum of the system and user CPU time of the current process. It does not include time elapsed during sleep. It is process-wide by definition. The reference point of the returned value is undefined, so that only the difference between the results of consecutive calls is valid.

`time.process_time()` only measures CPU processing time of `trt_yolo.detect()`.  However, the majority of the work, i.e. TensorRT inferencing, is done by the GPU (not counted as CPU processing time).

I think you should use something like `time.perf_counter()` to get a true measurement of processing time of `trt_yolo.detect()`.

> P.S.: Your yolov4_crowdhuman repo/tutorial seems like it's a custom trained version of yolov4-416, rather than yolov4-tiny-416. And the modified Marvel trailer video you shared with your custom yolov4_crowdhuman detector shows 30+ FPS speed on a Jetson Nano. So does that actually mean that I should somehow be able to get 30+ FPS with yolov4-416 on my Jetson Nano?

Sorry about the confusion.  I produced that Infinity War video on my desktop PC (RTX 2080 Ti).  The FPS number shown there does not reflect what's on Jetson Nano.
