### ISSUE TITLE
Ability to control MJPEG server bitrate

### ISSUE THREAD

**Issue by dvitrano** [jkjung-avt/tensorrt_demos#311]
Very interesting "variant" and easy way to share inference results over streaming. @jkjung-avt is there a way to control the MJPEG bitrate? the default is around 15Mbit/s for me. I found HD stream are still ok even with 50% of that bandwidth. Thanks !

_Originally posted by @dvitrano in https://github.com/jkjung-avt/tensorrt_demos/issues/217#issuecomment-751819603_

**Comment by jkjung-avt** [comment]
You could try to adjust the `_SLEEP_INTERVAL` in the code.

https://github.com/jkjung-avt/tensorrt_demos/blob/793d7ae9c74b51007296bb63cdd1bc6bd0e04e8e/utils/mjpeg.py#L21
