### ISSUE TITLE
Hello,

### ISSUE THREAD

**Issue by leeyunhome** [jkjung-avt/tensorrt_demos#319]
Hello, I converted yolov3 learned with pytorch to onnx

I converted yolov3 learned with pytorch to onnx. Is it possible to use the converted onnx file with GitHub project?

Thank you.

**Comment by jkjung-avt** [comment]
I have not tried it by myself.  Some other people have had success doing so: https://github.com/jkjung-avt/tensorrt_demos/issues/267#issuecomment-721714934
