### ISSUE TITLE
Multiple cameras at the same time

### ISSUE THREAD

**Issue by kubs0ne** [jkjung-avt/tensorrt_demos#329]
Hello,
I would like to make detections from 6 cameras at the same time using one script. Is it possible? I also have a question: how to rotate image from the camera by 180 degrees (the cameras are upside down). Is it possible to do with this library, or should I change options of the video output?

**Comment by jkjung-avt** [comment]
> I would like to make detections from 6 cameras at the same time using one script. Is it possible?

Yes.  Reference: [Capturing video from two cameras in OpenCV at once](https://stackoverflow.com/questions/29664399/capturing-video-from-two-cameras-in-opencv-at-once).

> how to rotate image from the camera by 180 degrees

1. Using GStreamer element: [videoflip](https://gstreamer.freedesktop.org/documentation/videofilter/videoflip.html?gi-language=c)
2. Using OpenCV API: [OpenCV Python – Rotate Image 90, 180, 270 – Example](https://www.tutorialkart.com/opencv/python/opencv-python-rotate-image/)
