### ISSUE TITLE
Makefile has directories which I don't have.

### ISSUE THREAD

**Issue by MatsalVistry** [jkjung-avt/tensorrt_demos#331]
The makefile in the plugins directory has TENSORRT_INCS=-I"/usr/local/TensorRT-7.1.3.4/include" while I don't even have /usr/local/TensorRT*. Is there something I'm missing or is there anything I have to change?

**Comment by jkjung-avt** [comment]
> TENSORRT_INCS=-I"/usr/local/TensorRT-7.1.3.4/include"

This is where I (manually) installed TensorRT libraries on my x86_64 PC.  It does not hurt if the path does not exist.

In case you have TensorRT libraries installed at another path, be sure to modify the Makefile accordingly.

**Comment by MatsalVistry** [comment]
So I ran 
$ sudo dpkg -i nv-tensorrt-repo-${os}-${tag}_1-1_amd64.deb
$ sudo apt-key add /var/nv-tensorrt-repo-${tag}/7fa2af80.pub
$ sudo apt-get update
$ sudo apt-get install tensorrt
$ sudo apt-get install python3-libnvinfer-dev

and I can't find any libs or include folder. Do I just leave it as it is and it should work?

**Comment by jkjung-avt** [comment]
If you are using a Jetson device, TensorRT should have been installed by JetPack already.

If you are using a x86_64 PC, refer to the official [TensorRT Installation Guide](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html).

When you install TensorRT with `apt-get install`, I think the library files would be located at "/usr/lib/x86_64-linux-gnu".  And you probably don't need to make any modification to the Makefile.

**Comment by MatsalVistry** [comment]
Got it, thank you so much!

**Comment by LiDe2000** [comment]
> If you are using a Jetson device, TensorRT should have been installed by JetPack already.
> 
> If you are using a x86_64 PC, refer to the official [TensorRT Installation Guide](https://docs.nvidia.com/deeplearning/tensorrt/install-guide/index.html).
> 
> When you install TensorRT with `apt-get install`, I think the library files would be located at "/usr/lib/x86_64-linux-gnu". And you probably don't need to make any modification to the Makefile.

I am using a Jetson Orin Nano, and TensorRT is already installed, but I cannot find the header file path.
