### ISSUE TITLE
A suggest to the repo

### ISSUE THREAD

**Issue by Alphonses** [jkjung-avt/tensorrt_demos#332]
Hello, @jkjung-avt. Can you add semantic segmentation algorithm to this project.Thank you sincerely.

**Comment by jkjung-avt** [comment]
Thanks for the good suggestion.  I will consider it.

**Comment by jkjung-avt** [comment]
@Alphonses  Check out my latest addition to this repo: [Demo \#7: MODNet](https://github.com/jkjung-avt/tensorrt_demos#modnet).

I think I could finally close this issue in a few days...
