### ISSUE TITLE
Regarding Custom Plugins

### ISSUE THREAD

**Issue by Darshcg** [jkjung-avt/tensorrt_demos#341]
Hi, @jkjung-avt,

Thanks for your great Work and continues Support. I have learnt a lot from your blogs and from your open-source implementations.

Actually, I am currently working on adding a custom plugin to the TRT. So, I am referring to your implementation of the Custom plugin for Yolov3 and yolov4. 

Having said that, I just want to understand how you are using the Custom Plugins here(https://github.com/jkjung-avt/tensorrt_demos/blob/master/yolo/plugins.py). I have understood that: after compiling yolo_layer.h and yolo_layer.cu, I will get the .so file, you are loading the .so(as a library) in plugins.py file. Is this right?

And also, why you are passing the 8 values under the Field_collection here: https://github.com/jkjung-avt/tensorrt_demos/blob/451208d77af78d66f0fcbd70802b8bea1701eb5e/yolo/plugins.py#L152 to create_plugin(). Where is that referenced in yolo_layer.cu?

And, lastly, may I know how the execution flow is going on in yolo_layer.cu?

Thanks in advance,
Darshan C G

**Comment by jkjung-avt** [comment]
> I have understood that: after compiling yolo_layer.h and yolo_layer.cu, I will get the .so file, you are loading the .so(as a library) in plugins.py file. Is this right?

Yes.  You could refer to: https://github.com/jkjung-avt/tensorrt_demos/blob/451208d77af78d66f0fcbd70802b8bea1701eb5e/yolo/plugins.py#L12-L17

> Where is that referenced in yolo_layer.cu?

https://github.com/jkjung-avt/tensorrt_demos/blob/451208d77af78d66f0fcbd70802b8bea1701eb5e/plugins/yolo_layer.cu#L352

> may I know how the execution flow is going on in yolo_layer.cu?

Please read NVIDIA's documentation and sample code of TensorRT plugins.
