### ISSUE TITLE
RuntimeError: Driver error: 

### ISSUE THREAD

**Issue by Darshcg** [jkjung-avt/tensorrt_demos#342]
Hi @jkjung-avt,

Thanks for your Materials. It helped me a lot.

I am converting from yolov3-288 onnx model to TRT, but whenever I am running:  **python3 onnx_to_tensorrt.py -m yolov3-288**  
I am getting an Issue as: 
```
Traceback (most recent call last):
  File "onnx_to_tensorrt.py", line 197, in <module>
    main()
  File "onnx_to_tensorrt.py", line 186, in main
    args.model, args.category_num, args.int8, args.dla_core, args.verbose)
  File "onnx_to_tensorrt.py", line 156, in build_engine
    engine = builder.build_engine(network, config)
RuntimeError: Driver error: 
```
May I know What is going wrong here?

Thanks

**Comment by jkjung-avt** [comment]
I think the problem is related to your TensorRT, cuDNN and CUDA installation.  You could refer to: https://github.com/NVIDIA/TensorRT/issues/875
