### ISSUE TITLE
FPS determined with which media?

### ISSUE THREAD

**Issue by rickymedrano** [jkjung-avt/tensorrt_demos#343]
In section 9 of here https://github.com/jkjung-avt/tensorrt_demos#demo-5-yolov4 
you list the FPS for the Nano of different models. Which video or image did you use with trt_yolo.py to get your FPS? I'm trying to reproduce the results. Thanks

**Comment by jkjung-avt** [comment]
I did the test using this [dog.jpg](https://raw.githubusercontent.com/AlexeyAB/darknet/master/data/dog.jpg) as input.

**Comment by rickymedrano** [comment]
Sounds good, thank you.
