### ISSUE TITLE
[Question] Best model for object detection

### ISSUE THREAD

**Issue by leviethung2103** [jkjung-avt/tensorrt_demos#346]
Hi author, 

First of all, thank you so much for creating this repository. It helps me a lot when I am getting to know the Jetson Nano and TensorRT. 

I've tested the SSD Model you provided. It achieved a very good FPS ~  24-26 FPS. However, I saw that the accuracy is not good in several cases. The model outputs a lot of False Positive detection. I am wondering that are there any alternatives for object detection problem which is better than SSD? 

Thank you in advance.

**Comment by jkjung-avt** [comment]
If you are looking to do real-time near 30FPS object detection on Jetson Nano, I think **yolov4-tiny** is the best choice right now.

**Comment by leviethung2103** [comment]
> If you are looking to do real-time near 30FPS object detection on Jetson Nano, I think **yolov4-tiny** is the best choice right now.

Thank you for your suggestion. I will try the Yolov4-tiny first.
