### ISSUE TITLE
UUF Convertor

### ISSUE THREAD

**Issue by PythonImageDeveloper** [jkjung-avt/tensorrt_demos#35]
Hi
I have some question:
1- What's the UUF converter? why we use this converter before converting to the TensorRT engine?
As you know we can convert the Tensorflow forzen graph (.pb) model to TernsorRT engine model directly and no need for UFF convertor, with TensorRT API:
```
trt_graph = trt.create_inference_graph(
    input_graph_def,
    outputs,
    max_batch_size,
    max_workspace_size_bytes,
    minimum_segment_size, 
    precision_mode="FP16") 
```
My quesion is that what's advantage of converting .pb (Tensorflow) >> . bin (UFF) >> .pb (TensorRT) instead .pb (Tensorflow) >>  .pb (TensorRT)?
2- The TensorRT library is optimization package for optimizing the graph, so the UFF library is optimizer also?  
3- what's host memory and cuda memory:
```
           size = trt.volume(self.engine.get_binding_shape(binding)) * self.engine.max_batch_size
            host_mem = cuda.pagelocked_empty(size, np.float32) 
            cuda_mem = cuda.mem_alloc(host_mem.nbytes)  
```
as far as I know, binding is the each of graph layers, and we get the size of each graph layers assigne the memory for each layers, but I don't what's host_mem?

**Comment by jkjung-avt** [comment]
Please read TensorRT documentation: https://docs.nvidia.com/deeplearning/sdk/tensorrt-developer-guide/index.html#api

Only Caffe, UFF and ONNX parsers are available in current releases of TensorRT.

**Comment by jkjung-avt** [comment]
Regarding your question 3 above,

- "bindings" refer to the inputs and outputs of a TensorRT engine
- For each binding, we allocate 1 "host" memory block and 1 "cuda" memory block.  The 2 memory blocks are of the same size.
- The "host" memory blocks should be blocks of contiguous memory location belonging to the CPU.
- Lilewise, the "cuda" memory blocks belong to the GPU.
- To do inference, we first copy image data to the input "host" memory.  This makes sure the data is contiguous and in the correct order.  Code: https://github.com/jkjung-avt/tensorrt_demos/blob/master/utils/ssd.py#L99
- Then we ask GPU to copy the data from "host" to "cuda" memory.  Code: https://github.com/jkjung-avt/tensorrt_demos/blob/master/utils/ssd.py#L101
- Next, we "execute" the Tensor engine.
- Finally, we copy the outputs from "cuda" back to "host" memory.
- Note that CUDA driver would make sure the memcpy's and engine execution are done sequentially (no race condition).
