### ISSUE TITLE
Can not convert the Custom trained Yolov3 model 

### ISSUE THREAD

**Issue by Myron1996** [jkjung-avt/tensorrt_demos#355]
Hi @jkjung-avt . I trained the custom **yolov3-416** model but unfortunately I can not convert it into **trt** using the provided scripts. 

I am getting the following error. 

`ERROR: bad category_num (80)`

Is there any modification I have to do to convert the custom models ?

I attached a `.cfg` file also for reference 

Thank you :-)

[yolov3-416.txt](https://github.com/jkjung-avt/tensorrt_demos/files/6037895/yolov3-416.txt)

**Comment by jkjung-avt** [comment]
As already stated in the README, please refer to [TensorRT YOLOv3 For Custom Trained Models](https://jkjung-avt.github.io/trt-yolov3-custom/).
