### ISSUE TITLE
Uff parameters for INT_8 precision?

### ISSUE THREAD

**Issue by siddharthrameshiisc** [jkjung-avt/tensorrt_demos#36]
Hey @jkjung-avt , so how do we create an .uff model with int8 precision forr SSD models? In build_engine.py file-->[https://github.com/jkjung-avt/tensorrt_demos/blob/master/ssd/build_engine.py](url)

It would be great if you could point out the relevant changes to be made.

Thanks

**Comment by jkjung-avt** [comment]
I haven't done it.  One of the main reasons is because Jetson Nano does not support INT8.

I think this is a good suggestion.  I might look into it later on.
