### ISSUE TITLE
Inference using .engine file from TLT 3.0

### ISSUE THREAD

**Issue by rickymedrano** [jkjung-avt/tensorrt_demos#365]
Hi,
I trained a Yolov4 model with Nvidia's TLT 3.0 and then decoupled it from TLT by using its [tlt-converter](https://docs.nvidia.com/metropolis/TLT/tlt-user-guide/text/object_detection/yolo_v4.html?highlight=yolov4#using-the-tlt-converter) to convert it to a TensorRT .engine file, on my Jetson Nano. 
Now that I have this .engine file, is there a way I can use it with your repo to do inference? Specifically with trt_yolo.py?

**Comment by jkjung-avt** [comment]
I think you could reuse most of the code, but most likely it won't work out of the box.  You mainly need to check what kind of preprocessing/postprocessing is needed for the TLT YOLOv4 model, and modify [utils/yolo_with_plugins.py](https://github.com/jkjung-avt/tensorrt_demos/blob/master/utils/yolo_with_plugins.py) accordingly.
