### ISSUE TITLE
Batch size fix for YOLO to ONNX

### ISSUE THREAD

**Issue by satyajitghana** [jkjung-avt/tensorrt_demos#373]
I was trying to convert yolov4-tiny darknet -> onnx -> tensorrt

onnx export was working fine, but when i set the `MAX_BATCH_SIZE = 9` in onnx_to_tensorrt it was throwing me

```
Loading the ONNX file...
Adding yolo_layer plugins...
Building an engine.  This would take a while...
(Use "--verbose" or "-v" to enable verbose logging.)
[TensorRT] ERROR: 009_route: all concat input tensors must have the same dimensions except on the concatenation axis (1), but dimensions mismatched at index 0. Input 0 shape: [9,64,256,256], Input 1 shape: [1,64,256,256]
[TensorRT] ERROR: 009_route: all concat input tensors must have the same dimensions except on the concatenation axis (1), but dimensions mismatched at index 0. Input 0 shape: [9,64,256,256], Input 1 shape: [1,64,256,256]
[TensorRT] ERROR: Layer 009_route failed validation
[TensorRT] ERROR: Network validation failed.
ERROR: failed to build the TensorRT engine!
```

so i had to change below line

https://github.com/jkjung-avt/tensorrt_demos/blob/94d06b356822dd230a969d8697dc8c3e55f0dfd6/yolo/yolo_to_onnx.py#L421

to `self.batch_size = 9` and then i exported my yolo to onnx, and then `onnx_to_tensorrt` worked with my required batch size !

consider adding a `MAX_BATCH_SIZE` in yolo_to_onnx 😄 

or add it as a argument to script

**Comment by jkjung-avt** [comment]
I have added MAX_BATCH_SIZE in "yolo_to_onnx.py": https://github.com/jkjung-avt/tensorrt_demos/commit/b42d70127a2374418a9e72fc32f2c063400ed7d2
