### ISSUE TITLE
Cuda Error in xxx: 77 (an illegal memory access was encountered)

### ISSUE THREAD

**Issue by boreas-l** [jkjung-avt/tensorrt_demos#376]
first，I feel so cool of your work. and i used the yolov3 part to accelerate inference successfully in your code. 

meanwhile,  i also do other try acoording to nvidia's blog.[https://developer.nvidia.com/blog/speeding-up-deep-learning-inference-using-tensorflow-onnx-and-tensorrt/](url). but when i run the code to do inference, I got some errors like as "cuda error in xxx: 77 (an illegal memory access was encountered)" . I am new in tensorRT and pycuda, i tried to find something solved，and just maybe of "pycuda thread". I tried it a little bit, but it didn't work out. i hope you can help me. thankyou.

i found you set "cuda_ctx = None" in yolo_with_plugins. and you dont use it? i cant understand. please give me some directions.thanks.

**Comment by jkjung-avt** [comment]
Please refer to [CUDA documentation](https://docs.nvidia.com/cuda/cuda-driver-api/group__CUDA__CTX.html) and [PyCUDA documentation](https://documen.tician.de/pycuda/).
