### ISSUE TITLE
Mtcnn with multiple faces

### ISSUE THREAD

**Issue by VLorin** [jkjung-avt/tensorrt_demos#377]
Hi, first of all great work! I'm working on Jetson nano and your implementation is the best I've seen for frontal face detection.But I have an issue (not sure if you can help), but I'm trying to do a face recognition using your mtcnn as a face detector, but sometime when I launch he can't see more than one or two faces at the time:
![facrec](https://user-images.githubusercontent.com/49037677/111181383-354d6380-85ae-11eb-9b2c-cfea9ce11470.png)
But some other time it works perfectly fine :
![facrec2](https://user-images.githubusercontent.com/49037677/111181461-4bf3ba80-85ae-11eb-911b-5c6201316350.png)
Between the two pictures I've just stopped and restarted the same program without making any modification. 
Can you help me with this ? Thx
I've didn't modify your code related to the mtcnn, I just use `mtcnn.detect()` in my code

**Comment by jkjung-avt** [comment]
I think you are facing a known issue as described here: https://github.com/jkjung-avt/tensorrt_demos/issues/313#issuecomment-787648496

Please try to use a different version of TensorRT (don't use 7.1.3.4).

**Comment by VLorin** [comment]
Thx you for your response ! Will try soon
