### ISSUE TITLE
DeepStream Integration for your Project Demos

### ISSUE THREAD

**Issue by Darshcg** [jkjung-avt/tensorrt_demos#378]
Hi @jkjung-avt,

Thanks for all your Projects. 
I wanted to know about the Deepstream Integration for your Project. Did you work on that? Anyone have Implemented that?

Thanks,
Darshan

**Comment by jkjung-avt** [comment]
I have an implementation of DeepStream 5.x glue code at work for the TensorRT yolov4/yolov4-tiny engines created by this repo.  So I know it would work.

I cannot share the DeepStream code, though.

**Comment by Darshcg** [comment]
Hi @jkjung-avt,

I have integrated the DeepStream for all your Yolo models.

Thanks

**Comment by jkjung-avt** [comment]
Sounds good.
