### ISSUE TITLE
yolov4 tensorrt with ROS : (pycuda error) context stack was not empty upon module clean

### ISSUE THREAD

**Issue by indra4837** [jkjung-avt/tensorrt_demos#379]
Hi, great work on your tensorrt_demos! You can find my code [here](https://github.com/indra4837/yolov4_trt_ros)

I adapted your work to ROS for my project use and achieve great results with it. However, I am always receiving a pycuda error after the program is killed. Do refer to the screenshot for a sample error log found. 

![image](https://user-images.githubusercontent.com/64070777/111585246-00355100-87fa-11eb-9a45-08d20e0a064d.png)

**Comment by jkjung-avt** [comment]
@indra4837  Could you provide a simpler example (say, with only minor modifications to my original trt_yolo.py) to reproduce this problem?

**Comment by jkjung-avt** [comment]
Closing due to no response.
