### ISSUE TITLE
jetson tx2 yolov3_to_onnx.py bug

### ISSUE THREAD

**Issue by Gaondong** [jkjung-avt/tensorrt_demos#39]
![IMG_4909](https://user-images.githubusercontent.com/43692998/72197445-64bd8900-345c-11ea-847c-0de3c786ed51.JPG)
I run the script yolov3_to_onnx.py  on jetsontx2 with jetpack4.2.1 onnx=1.4.1 and it still show the above code without change.

**Comment by jkjung-avt** [comment]
Did you run 'download_yolov3.sh' script as described in step 3 of [Demo #4](https://github.com/jkjung-avt/tensorrt_demos#yolov3)?

```
$ cd ${HOME}/project/tensorrt_demos/yolov3_onnx
$ ./download_yolov3.sh
```

**Comment by Gaondong** [comment]
> Did you run 'download_yolov3.sh' script as described in step 3 of [Demo #4](https://github.com/jkjung-avt/tensorrt_demos#yolov3)?
> 
> ```
> $ cd ${HOME}/project/tensorrt_demos/yolov3_onnx
> $ ./download_yolov3.sh
> ```

Thanks for your reply,  I just wait for a long time and it runs normally.
I think this is because the Compute Capability of tx2‘s CPU is not enough
