### ISSUE TITLE
Yolov4Tiny running slow on Jetson Nano with TensorRT

### ISSUE THREAD

**Issue by MatsalVistry** [jkjung-avt/tensorrt_demos#392]
Same issue as title. I have configured my entire environment and run the tensorrt_demos repository with both your pre-trained model and my custom model and got around 5-7 fps. On your examples you said you achieved 25.5 fps using the yolov4tiny model so I was wondering if you have any idea why my model is underperforming. I am running on a fresh brand new jetson nano with only the basic environment setup needed to run the project. Thank you!

**Comment by jkjung-avt** [comment]
https://github.com/jkjung-avt/tensorrt_demos/issues/380#issuecomment-810779712
