### ISSUE TITLE
Cannot convert onnx to trt (yolo-csp-256 with single class cfg)

### ISSUE THREAD

**Issue by ksy961224** [jkjung-avt/tensorrt_demos#393]
Hi Sir,
I have issue with converting modified yolov4-csp-256.onnx to TensorRT format, which has different custom class number (classes=1, filter=18, nothing else edited at all)

I have no problem with converting default yolov4-csp-256.onnx to trt file
but can't convert modified-yolov4-csp-256.onnx to trt file
During parsing onnx file, Segmentation fault error occurs

>...
 [TensorRT] VERBOSE: ImporterContext.hpp:116: Registering tensor: 174_convolutional for ONNX tensor: 174_convolutional
[TensorRT] VERBOSE: ModelImporter.cpp:179: 174_convolutional [Conv] outputs: [174_convolutional -> (1, 18, 8, 8)], 
[TensorRT] VERBOSE: ModelImporter.cpp:103: Parsing node: 174_convolutional_lgx [Sigmoid]
[TensorRT] VERBOSE: ModelImporter.cpp:119: Searching for input: 174_convolutional
[TensorRT] VERBOSE: ModelImporter.cpp:125: 174_convolutional_lgx [Sigmoid] inputs: [174_convolutional -> (1, 18, 8, 8)], 
[TensorRT] VERBOSE: ImporterContext.hpp:141: Registering layer: 174_convolutional_lgx for ONNX node: 174_convolutional_lgx
[TensorRT] VERBOSE: ImporterContext.hpp:116: Registering tensor: 174_convolutional_lgx for ONNX tensor: 174_convolutional_lgx
[TensorRT] VERBOSE: ModelImporter.cpp:179: 174_convolutional_lgx [Sigmoid] outputs: [174_convolutional_lgx -> (1, 18, 8, 8)], 
[TensorRT] VERBOSE: ModelImporter.cpp:507: Marking 139_convolutional_1 as output: 139_convolutional
[TensorRT] VERBOSE: ModelImporter.cpp:507: Marking 150_convolutional_1 as output: 150_convolutional
Segmentation fault

I've seen the answer that can be caused by oom, So I did same job on Google Colab.
 But same happens (default onnx can be converted on colab too)

I trained with cfg with 512size, and 
used 256cfg with 512weight file during converting, as same as default code does.

Is there any possible way to solve it?
Anyway, I really appreciate ur code

[yolov4-csp-256-numplate_cfg.zip](https://github.com/jkjung-avt/tensorrt_demos/files/6334262/yolov4-csp-256-numplate.zip)
yolov4-numplate-csp-256.onnx : https://drive.google.com/file/d/1AgyKtS8zMC2sHHklpOBJQ2Ygjgylc0gg/view?usp=sharing

**Comment by jkjung-avt** [comment]
Please rename your DarkNet model files as "yolov4-csp-numplate-256.cfg" and "yolov4-csp-numplate-256.weights".  Then re-run "yolo_to_onnx.py"

```shell
$ python3 yolo_to_onnx.py -c 1 -m yolov4-csp-numplate-256
```

The relevant source code is here: https://github.com/jkjung-avt/tensorrt_demos/blob/4b26770dca33cbe613f65e9b64ec3b9c912e2084/yolo/yolo_to_onnx.py#L946-L949

**Comment by ksy961224** [comment]
Thanks a lot. :)
I havent tried converting cfg to onnx with name chaning
