### ISSUE TITLE
Running Multiple Models on Xavier NX

### ISSUE THREAD

**Issue by Darshcg** [jkjung-avt/tensorrt_demos#394]
Hi @jkjung-avt,

Is it Possible to run multiple Models parallelly on Xavier NX Board?
How about running one model on DLA0, another  on DLA1, and another on GPU in parallel?

Thanks,
Darshan

**Comment by jkjung-avt** [comment]
Yes.  You could just invoke multiple instances of "trt_yolo.py".

Running 1 yolo engine on DLA0, another on DLA1 and the 3rd one on GPU does not work too well (on Xavier NX at least).  There are at least 2 problems:

1. There is [no TensorRT Python API for setting DLA core for inference](https://forums.developer.nvidia.com/t/no-method-in-tensorrt-python-api-for-setting-dla-core-for-inference/155874).
2. The yolo engines don't work well on DLA.  A lot of the layers are "fallen-back" to GPU.  So the GPU gets overloaded anyway.  Refer to: https://github.com/jkjung-avt/tensorrt_demos/issues/364
