### ISSUE TITLE
Error while build onnx file

### ISSUE THREAD

**Issue by gioriog** [jkjung-avt/tensorrt_demos#398]
Hello, I am trying to convert a yolo custom model to an onnx format and use it for a unity application. I run into this error about some Upsample layer. Is there something I can fix from cfg file ?

Checking ONNX model...
Traceback (most recent call last):
  File "yolo_to_onnx.py", line 987, in <module>
    main()
  File "yolo_to_onnx.py", line 977, in main
    onnx.checker.check_model(yolo_model_def)
  File "/home/cim40/anaconda3/lib/python3.8/site-packages/onnx/checker.py", line 104, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Op registered for Upsample is deprecated in domain_version of 14

==> Context: Bad node spec for node. Name: 086_upsample OpType: Upsample

Also, this may be because I had installed onnx version 1.9. 
I tried to install onnx==1.4.1 (pip install onnx==1.4.1) but I get some errors too:

 subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '28']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/cim40/anaconda3/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bnjy79yo/onnx_f7afeb7a244042a196acbe119bf210d9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-bnjy79yo/onnx_f7afeb7a244042a196acbe119bf210d9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-k9f55x9b/install-record.txt --single-version-externally-managed --compile --install-headers /home/c/anaconda3/include/python3.8/onnx Check the logs for full command output.

[yolov3-custom-416.zip](https://github.com/jkjung-avt/tensorrt_demos/files/6376928/yolov3-custom-416.zip)

**Comment by jkjung-avt** [comment]
Please refer to https://github.com/jkjung-avt/tensorrt_demos/issues/70.  You have to use onnx==1.4.1 for yolo models in thos repo.

> subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '28']' returned non-zero exit status 2.
> 
> ERROR: Command errored out with exit status 1: /home/cim40/anaconda3/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-bnjy79yo/onnx_f7afeb7a244042a196acbe119bf210d9/setup.py'"'"'; file='"'"'/tmp/pip-install-bnjy79yo/onnx_f7afeb7a244042a196acbe119bf210d9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(file) if os.path.exists(file) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, file, '"'"'exec'"'"'))' install --record /tmp/pip-record-k9f55x9b/install-record.txt --single-version-externally-managed --compile --install-headers /home/c/anaconda3/include/python3.8/onnx Check the logs for full command output.

What's the exact error you encountered when installing onnx==1.4.1?  Could you dig out the log file?

**Comment by gioriog** [comment]
Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Collecting onnx==1.4.1
  Downloading onnx-1.4.1.tar.gz (2.9 MB)
     |████████████████████████████████| 2.9 MB 5.6 MB/s 
Requirement already satisfied: protobuf in ./anaconda3/lib/python3.8/site-packages (from onnx==1.4.1) (3.15.8)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.8/site-packages (from onnx==1.4.1) (1.19.2)
Requirement already satisfied: six in ./anaconda3/lib/python3.8/site-packages (from onnx==1.4.1) (1.15.0)
Requirement already satisfied: typing>=3.6.4 in ./anaconda3/lib/python3.8/site-packages (from onnx==1.4.1) (3.7.4.3)
Requirement already satisfied: typing-extensions>=3.6.2.1 in ./anaconda3/lib/python3.8/site-packages (from onnx==1.4.1) (3.7.4.3)
Building wheels for collected packages: onnx
  Building wheel for onnx (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/cim40/anaconda3/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/setup.py'"'"'; __file__='"'"'/tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-t2d3_42g
       cwd: /tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/
  Complete output (127 lines):
  fatal: not a git repository (or any of the parent directories): .git
  /home/cim40/anaconda3/lib/python3.8/site-packages/setuptools/dist.py:642: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
    warnings.warn(
  /home/cim40/anaconda3/lib/python3.8/site-packages/setuptools/dist.py:642: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
    warnings.warn(
  running bdist_wheel
  running build
  running build_py
  running create_version
  running cmake_build
  -- Build type not set - defaulting to Release
  -- The C compiler identification is GNU 9.3.0
  -- The CXX compiler identification is GNU 9.3.0
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found Protobuf: /home/cim40/anaconda3/lib/libprotobuf.so (found version "3.14.0")
  CMake Warning at CMakeLists.txt:356 (find_package):
    By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
    asked CMake to find a package configuration file provided by "pybind11",
    but CMake did not find one.
  
    Could not find a package configuration file provided by "pybind11"
    (requested version 2.2) with any of the following names:
  
      pybind11Config.cmake
      pybind11-config.cmake
  
    Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
    "pybind11_DIR" to a directory containing one of the above files.  If
    "pybind11" provides a separate development package or SDK, be sure it has
    been installed.
  
  
  --
  -- ******** Summary ********
  --   CMake version         : 3.18.4
  --   CMake command         : /usr/local/lib/python3.8/dist-packages/cmake/data/bin/cmake
  --   System                : Linux
  --   C++ compiler          : /usr/bin/c++
  --   C++ compiler version  : 9.3.0
  --   CXX flags             :  -Wnon-virtual-dtor
  --   Build type            : Release
  --   Compile definitions   :
  --   CMAKE_PREFIX_PATH     :
  --   CMAKE_INSTALL_PREFIX  : /usr/local
  --   CMAKE_MODULE_PATH     :
  --
  --   ONNX version          : 1.4.1
  --   ONNX NAMESPACE        : onnx
  --   ONNX_BUILD_TESTS      : OFF
  --   ONNX_BUILD_BENCHMARKS : OFF
  --   ONNX_USE_LITE_PROTO   : OFF
  --   ONNXIFI_DUMMY_BACKEND : OFF
  --
  --   Protobuf compiler     : /home/cim40/anaconda3/bin/protoc
  --   Protobuf includes     : /home/cim40/anaconda3/include
  --   Protobuf libraries    : /home/cim40/anaconda3/lib/libprotobuf.so
  --   BUILD_ONNX_PYTHON     : ON
  --     Python version      :
  --     Python executable   : /home/cim40/anaconda3/bin/python3
  --     Python includes     : /home/cim40/anaconda3/include/python3.8
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/.setuptools-cmake-build
  Scanning dependencies of target gen_onnx_proto
  Scanning dependencies of target onnxifi_loader
  Scanning dependencies of target onnxifi_dummy
  [  1%] Running gen_proto.py on onnx/onnx.in.proto
  [  3%] Building C object CMakeFiles/onnxifi_loader.dir/onnx/onnxifi_loader.c.o
  [  5%] Building C object CMakeFiles/onnxifi_dummy.dir/onnx/onnxifi_dummy.c.o
  Processing /tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/onnx/onnx.in.proto
  Writing /tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/.setuptools-cmake-build/onnx/onnx.proto
  Writing /tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/.setuptools-cmake-build/onnx/onnx.proto3
  generating /tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/.setuptools-cmake-build/onnx/onnx_pb.py
  [  7%] Linking C static library libonnxifi_loader.a
  [  9%] Running C++ protocol buffer compiler on /tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/.setuptools-cmake-build/onnx/onnx.proto
  --python_out: onnx/onnx.proto: Unknown generator option: dllexport_decl
  make[2]: *** [CMakeFiles/gen_onnx_proto.dir/build.make:81: onnx/onnx.pb.cc] Error 1
  make[1]: *** [CMakeFiles/Makefile2:134: CMakeFiles/gen_onnx_proto.dir/all] Error 2
  make[1]: *** Waiting for unfinished jobs....
  [  9%] Built target onnxifi_loader
  [ 11%] Linking C shared library libonnxifi_dummy.so
  [ 11%] Built target onnxifi_dummy
  make: *** [Makefile:149: all] Error 2
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/setup.py", line 309, in <module>
      setuptools.setup(
    File "/home/cim40/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "/home/cim40/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/cim40/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/cim40/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/cim40/anaconda3/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "/home/cim40/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/cim40/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/cim40/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/home/cim40/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/cim40/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/setup.py", line 203, in run
      self.run_command('cmake_build')
    File "/home/cim40/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/home/cim40/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/setup.py", line 197, in run
      subprocess.check_call(build_args)
    File "/home/cim40/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '28']' returned non-zero exit status 2.
  ----------------------------------------
  ERROR: Failed building wheel for onnx
  Running setup.py clean for onnx
Failed to build onnx
Installing collected packages: onnx
    Running setup.py install for onnx ... error
    ERROR: Command errored out with exit status 1:
     command: /home/cim40/anaconda3/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/setup.py'"'"'; __file__='"'"'/tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-hjdpm35p/install-record.txt --single-version-externally-managed --compile --install-headers /home/cim40/anaconda3/include/python3.8/onnx
         cwd: /tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/
    Complete output (107 lines):
    fatal: not a git repository (or any of the parent directories): .git
    /home/cim40/anaconda3/lib/python3.8/site-packages/setuptools/dist.py:642: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
      warnings.warn(
    /home/cim40/anaconda3/lib/python3.8/site-packages/setuptools/dist.py:642: UserWarning: Usage of dash-separated 'license-file' will not be supported in future versions. Please use the underscore name 'license_file' instead
      warnings.warn(
    running install
    running build
    running build_py
    running create_version
    running cmake_build
    CMake Warning at CMakeLists.txt:356 (find_package):
      By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "pybind11",
      but CMake did not find one.
    
      Could not find a package configuration file provided by "pybind11"
      (requested version 2.2) with any of the following names:
    
        pybind11Config.cmake
        pybind11-config.cmake
    
      Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
      "pybind11_DIR" to a directory containing one of the above files.  If
      "pybind11" provides a separate development package or SDK, be sure it has
      been installed.
    
    
    --
    -- ******** Summary ********
    --   CMake version         : 3.18.4
    --   CMake command         : /usr/local/lib/python3.8/dist-packages/cmake/data/bin/cmake
    --   System                : Linux
    --   C++ compiler          : /usr/bin/c++
    --   C++ compiler version  : 9.3.0
    --   CXX flags             :  -Wnon-virtual-dtor
    --   Build type            : Release
    --   Compile definitions   :
    --   CMAKE_PREFIX_PATH     :
    --   CMAKE_INSTALL_PREFIX  : /usr/local
    --   CMAKE_MODULE_PATH     :
    --
    --   ONNX version          : 1.4.1
    --   ONNX NAMESPACE        : onnx
    --   ONNX_BUILD_TESTS      : OFF
    --   ONNX_BUILD_BENCHMARKS : OFF
    --   ONNX_USE_LITE_PROTO   : OFF
    --   ONNXIFI_DUMMY_BACKEND : OFF
    --
    --   Protobuf compiler     : /home/cim40/anaconda3/bin/protoc
    --   Protobuf includes     : /home/cim40/anaconda3/include
    --   Protobuf libraries    : /home/cim40/anaconda3/lib/libprotobuf.so
    --   BUILD_ONNX_PYTHON     : ON
    --     Python version      :
    --     Python executable   : /home/cim40/anaconda3/bin/python3
    --     Python includes     : /home/cim40/anaconda3/include/python3.8
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/.setuptools-cmake-build
    [  3%] Built target onnxifi_loader
    [  5%] Running C++ protocol buffer compiler on /tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/.setuptools-cmake-build/onnx/onnx.proto
    [  9%] Built target onnxifi_dummy
    Scanning dependencies of target onnxifi_wrapper
    [ 11%] Building C object CMakeFiles/onnxifi_wrapper.dir/onnx/onnxifi_wrapper.c.o
    --python_out: onnx/onnx.proto: Unknown generator option: dllexport_decl
    make[2]: *** [CMakeFiles/gen_onnx_proto.dir/build.make:81: onnx/onnx.pb.cc] Error 1
    make[1]: *** [CMakeFiles/Makefile2:134: CMakeFiles/gen_onnx_proto.dir/all] Error 2
    make[1]: *** Waiting for unfinished jobs....
    [ 12%] Linking C shared module libonnxifi.so
    [ 12%] Built target onnxifi_wrapper
    make: *** [Makefile:149: all] Error 2
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/setup.py", line 309, in <module>
        setuptools.setup(
      File "/home/cim40/anaconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/home/cim40/anaconda3/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/home/cim40/anaconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/home/cim40/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/cim40/anaconda3/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/cim40/anaconda3/lib/python3.8/distutils/command/install.py", line 545, in run
        self.run_command('build')
      File "/home/cim40/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/cim40/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/home/cim40/anaconda3/lib/python3.8/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/home/cim40/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/cim40/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/setup.py", line 203, in run
        self.run_command('cmake_build')
      File "/home/cim40/anaconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/home/cim40/anaconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/setup.py", line 197, in run
        subprocess.check_call(build_args)
      File "/home/cim40/anaconda3/lib/python3.8/subprocess.py", line 364, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['/usr/local/bin/cmake', '--build', '.', '--', '-j', '28']' returned non-zero exit status 2.
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/cim40/anaconda3/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/setup.py'"'"'; __file__='"'"'/tmp/pip-install-v1vncfxm/onnx_4b4b637c32964d11afe6a11a8d86a354/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-hjdpm35p/install-record.txt --single-version-externally-managed --compile --install-headers /home/cim40/anaconda3/include/python3.8/onnx Check the logs for full command output.



This is the full output while installing onnx==1.4.1. My python version is 3.8.5. 
I didnt manage to find where the log file is located

**Comment by gioriog** [comment]
[log.txt](https://github.com/jkjung-avt/tensorrt_demos/files/6377543/log.txt)

I didnt manage to find the log file so I am reporting all the output after the command: pip3 install onnx==1.4.1
I am currently using python 3.8.5, maybe I have to downgrade it ? If so how and which version ?

**Comment by jkjung-avt** [comment]
Python 3.8.5 should work.  You don't need to downgrade it.

I think the problem you should solve first is the following error.  Check if this helps: https://github.com/onnx/onnx/issues/1624#issuecomment-799314072

>     CMake Warning at CMakeLists.txt:356 (find_package):
>       By not providing "Findpybind11.cmake" in CMAKE_MODULE_PATH this project has
>       asked CMake to find a package configuration file provided by "pybind11",
>       but CMake did not find one.
>     
>       Could not find a package configuration file provided by "pybind11"
>       (requested version 2.2) with any of the following names:
>     
>         pybind11Config.cmake
>         pybind11-config.cmake
>     
>       Add the installation prefix of "pybind11" to CMAKE_PREFIX_PATH or set
>       "pybind11_DIR" to a directory containing one of the above files.  If
>       "pybind11" provides a separate development package or SDK, be sure it has
>       been installed.

**Comment by gioriog** [comment]
Running: sudo pip3 install onnx==1.4.1
Requirement already satisfied: onnx==1.4.1 in /usr/local/lib/python3.8/dist-packages (1.4.1)
Requirement already satisfied: six in /usr/lib/python3/dist-packages (from onnx==1.4.1) (1.14.0)
Requirement already satisfied: numpy in /usr/lib/python3/dist-packages (from onnx==1.4.1) (1.17.4)
Requirement already satisfied: typing-extensions>=3.6.2.1 in /usr/local/lib/python3.8/dist-packages (from onnx==1.4.1) (3.7.4.3)
Requirement already satisfied: protobuf in /usr/lib/python3/dist-packages (from onnx==1.4.1) (3.6.1)
Requirement already satisfied: typing>=3.6.4 in /usr/local/lib/python3.8/dist-packages (from onnx==1.4.1) (3.7.4.3)

Seems like it is installed but when I open a python shell and type import onnx, it does not find the module. Maybe I should set some environment variable ?

**Comment by jkjung-avt** [comment]
It looks like your "onnx==1.4.1" has been installed at "/usr/local/lib/python3.8/dist-packages".  You should be able to verify that with `pip3 show onnx`.

Otherwise, are you running python in a conda environment?  Make sure "/usr/local/lib/python3.8/dist-packages" is in your python module search paths (`sys.path`).

**Comment by gioriog** [comment]
I think I have solved the issue. I had to run python3 yolo_to_onnx.py into sudo python environment instead of python3 yolo_to_onnx.py. Thank you al lot for the advices.

**Comment by jkjung-avt** [comment]
https://github.com/jkjung-avt/tensorrt_demos/issues/539#issuecomment-1119218462

**Comment by NaveenVSeeWise** [comment]
I have facing the issue with yolo to onnx conversion using yolov3 tiny pre-trained model.
python3 yolo_to_onnx.py -m yolov3-tiny-288
Parsing DarkNet cfg file...
Building ONNX graph...
Traceback (most recent call last):
  File "yolo_to_onnx.py", line 1065, in <module>
    main()
  File "yolo_to_onnx.py", line 1053, in main
    verbose=True)
  File "yolo_to_onnx.py", line 590, in build_onnx_graph
    params)
  File "yolo_to_onnx.py", line 414, in load_resize_scales
    name, TensorProto.FLOAT, shape, data)
  File "/home/nano/.local/lib/python3.6/site-packages/onnx/helper.py", line 254, in make_tensor
    getattr(tensor, field).extend(vals)
TypeError: 1.0 has type numpy.float32, but expected one of: int, long, float
