### ISSUE TITLE
Model Convert Error

### ISSUE THREAD

**Issue by LK007CX** [jkjung-avt/tensorrt_demos#406]
I try to use a trt model (which was converted in device A) to run in another  device B.
But the fact is that i can not use a trt model that was converted in another device.
The logger info is below.
[TensorRT] WARNING: Using an engine plan file across different models of devices is not recommended and is likely to affect performance or even cause errors.

How can I solve this question?
Thanks!

**Comment by jkjung-avt** [comment]
Please refer to NVIDIA's official TensorRT documentation: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#error-messaging

> Error message: Builder was created on device different from current device.
> 
> Description: This error message may show up if you: (1) Created an IBuilder targeting one GPU, then (2)
> Called cudaSetDevice() to target a different GPU, then (3) Attempted to use the IBuilder to create an engine.  Ensure you only use the IBuilder when targeting the GPU that was used to create the IBuilder.

You should always build a TensorRT engine and do inference with it on the exact same model of GPU.
