### ISSUE TITLE
Convert onnex to trt crashes the system.

### ISSUE THREAD

**Issue by maldivien** [jkjung-avt/tensorrt_demos#427]
This issue is consistent with some models.

I use AGX Xavier, might be a problem with power? I'm using max settings.

Can I convert to trt using a PC?

**Comment by maldivien** [comment]
I'm using a yolov3 model, conversion to onnex was a success. Demos works as expected with very high frame rates so i dont think this a installation issue.

**Comment by jkjung-avt** [comment]
Please use the "--verbose" (or "-v") command-line option and share the crash log.

**Comment by maldivien** [comment]
Thanks. I have found the problem. It's due to insufficient/inconsistent power supply. AGX Xavier requires a very stable 65W power supply to run at MAX settings.

BTW I have question regarding NVDLA, what's the advantage of using it as it doesn't show any performance gains.

**Comment by jkjung-avt** [comment]
> BTW I have question regarding NVDLA, what's the advantage of using it as it doesn't show any performance gains.

Please refer to https://github.com/jkjung-avt/tensorrt_demos/issues/364.
