### ISSUE TITLE
The target is detected but the saved picture is not clear 

### ISSUE THREAD

**Issue by kaiven11** [jkjung-avt/tensorrt_demos#430]
os:ubuntu 18.04 LTS
cuda:10.2
tensorrt:7.0.0.1
rtsp:18 channels
Graphics card ：tesla T4

As the title says, when I detect the target of interest, I save the picture, but the face in the picture is very blurry. I guess it should not be the problem of the camera. My camera setting is 1920x1080, 25 frames. Could you please provide me an idea ？

![1623002223(1)](https://user-images.githubusercontent.com/25794106/120935117-c8241700-c733-11eb-8dcf-f207277d0da6.jpg)

**Comment by jkjung-avt** [comment]
You could use the command-line option "--width 1080 --height 1920" of trt_yolo.py.
