### ISSUE TITLE
load two models report errors

### ISSUE THREAD

**Issue by kaiven11** [jkjung-avt/tensorrt_demos#431]
I used a yolov3 trt engine  And a yolov5 trt engine, I tested  both of them  separately and everything is ok.

When put them togethor,Report the below error:

![image](https://user-images.githubusercontent.com/25794106/121119975-3c9fa880-c84f-11eb-892a-3ef799fe052f.png)

I did not change code in  the yolo_with_plugins.py ,
Only  flollow the https://github.com/jkjung-avt/tensorrt_demos/issues/203#issuecomment-680077788 ,change code in the yolov5_trt.py(this is my custom yolov5 file)

yolov5_trt.py file:

[yolov5_trt.txt](https://github.com/jkjung-avt/tensorrt_demos/files/6613376/yolov5_trt.txt)

**Comment by jkjung-avt** [comment]
Please try the code snippet here: https://github.com/jkjung-avt/tensorrt_demos/issues/219#issuecomment-695429092

If it works, then the problem is likely due to either: 1. the TensorRT yolov5 engine is not built correctly, or, 2. bug in your code.

**Comment by jkjung-avt** [comment]
I have no idea about "./build/libmyplugins.so".  I would have checked if there are name conflicts between the 2 so files...

**Comment by kaiven11** [comment]
sorry, I follow the  https://github.com/wang-xinyu/tensorrtx/tree/yolov5-v3.0/yolov5  to gender yolov5.trt file and  the  .so file .

I just copy the file to this project.

**Comment by jkjung-avt** [comment]
As stated earlier, you'll have to resolve naming conflicts between the 2 .so files by yourself.

**Comment by kaiven11** [comment]
I edit the two  yolo_layer.cu file,  one for yolov3,another for yolov5 , 
 1.change the namespace  yolo3  and yolo5  , 
 2. one change  YoloLayerPlugin to YoloLayerPlugin3 , another YoloLayerPlugin5
 3. make success
 4. test separately (success)
 5. test together (fail)
 
error message:
![image](https://user-images.githubusercontent.com/25794106/121172159-f9aef680-c889-11eb-8f03-9395df13049b.png)


Maybe can't init the nvinfer1 two times?
Pls give me some advice, Thank you.

**Comment by jkjung-avt** [comment]
The 2 plugins cannot register the same name and version.  After you modify plugin name of one of them, you need to re-build the TensorRT engine with the updated name.

https://github.com/jkjung-avt/tensorrt_demos/blob/bac5085d75e59369cc587cf9ec19f5120836cb3e/plugins/yolo_layer.cu#L337-L345
