### ISSUE TITLE
make does not work 

### ISSUE THREAD

**Issue by Myron1996** [jkjung-avt/tensorrt_demos#433]
Hi @jkjung-avt . I am trying to run `make` command in plugins directory but I am receiving following error .  Can you please advice me on this ? Thank you 
```
Makefile:20: "compute=75" is for GeForce RTX-2080 Ti.  Please make sure CUDA compute is set correctly for your system in the Makefile.
g++ -shared -o libyolo_layer.so yolo_layer.o -L"/usr/local/cuda/lib64" -L"/usr/local/TensorRT-7.1.3.4/lib" -L"/usr/local/lib" -Wl,--start-group -lnvinfer -lnvparsers -lnvinfer_plugin -lcudnn -lcublas -lcudart_static -lnvToolsExt -lcudart -lrt -ldl -lpthread -Wl,--end-group
/usr/bin/ld: cannot find -lnvparsers
/usr/bin/ld: cannot find -lnvinfer_plugin
collect2: error: ld returned 1 exit status
Makefile:45: recipe for target 'libyolo_layer.so' failed
make: *** [libyolo_layer.so] Error 1

```

**Comment by jkjung-avt** [comment]
> /usr/bin/ld: cannot find -lnvparsers
> /usr/bin/ld: cannot find -lnvinfer_plugin

This means "ld" was not able to find your TensorRT libraries ("libnvparsers.so" and "libnvinfer_plugin").  You should check your TensorRT installation.

**Comment by Myron1996** [comment]
Sure , I thought the same. Thank you Bro. I will look in to it.

**Comment by Myron1996** [comment]
It was tensorrt installation fault . It's been resolved

**Comment by rafaelbate** [comment]
> It was tensorrt installation fault . It's been resolved

Hello @Myron1996, having the same issue when trying to install in Google Colab .. Could you tell me what was your fix? Where is tensorrt located? Thanks :)

**Comment by Myron1996** [comment]
Hi @rafaelbate . I actually used a docker image which has all the dependency's installed .I was working on local machine. 

You can check following repo. It will show you how to install the docker image. I hope it helps 

https://github.com/GeekAlexis/FastMOT/blob/master/README.md

**Comment by rafaelbate** [comment]
Thanks @Myron1996, I got it running using WSL2 and docker as you mentioned :)
