### ISSUE TITLE
Demo #5 - ImportError when running yolo_to_onnx.py

### ISSUE THREAD

**Issue by Amaan24** [jkjung-avt/tensorrt_demos#439]
When trying to run the line 
python3 yolo_to_onnx.py -m yolov4-416, I get ImportError: cannot import name 'enum_type_wrapper'. Any ideas of how to fix?

**Comment by jkjung-avt** [comment]
Please provide the complete error log (traceback).

**Comment by Amaan24** [comment]
Error was due to files from old version of protobuf on my system. Removing all protobuf files and re-installing fixed the issue
