### ISSUE TITLE
ERROR: nvcc not found with tensorflow-1.15 and jetpack-4.3

### ISSUE THREAD

**Issue by PythonImageDeveloper** [jkjung-avt/tensorrt_demos#44]
Hi,
I used your wheel TensorFlow 1.15 file for install and correctly is install. but when I run **./install.sh** in ssd folder, I get this error:

> ERROR: nvcc not found
> ** Patch 'graphsurgeon.py' in TensorRT
> patching file /usr/lib/python3.6/dist-packages/graphsurgeon/node_manipulation.py
> 
> ** Making symbolic link of libflattenconcat.so
> ** Installation done

I comment this lines in install_pycuda.sh

> if ! which nvcc > /dev/null; then
>   echo "ERROR: nvcc not found"
>   exit
> fi

then I run the 

`python3 trt_ssd.py --model ssd_mobilenet_v2_egohands --image --filename hand.jpg`

The output is ok and correctly I get the result but I get this error during the run the above python command :

> [TensorRT] ERROR: Could not register plugin creator:  FlattenConcat_TRT in namespace: 

I get about 20 FPS when I run **trt_ssd.py**  for ssd_mobilenet_v2_egohands model and I get about 2 27 FPS when I run **trt_ssd_async.py**, but I get more FPS with Tensorflow-1.12.2 Jetpack-4.2.2, even I get 30 FPS  with run **python3 trt_ssd.py --model ssd_mobilenet_v2_egohands --image --filename hand.jpg** and 35 FPS with **trt_ssd_async.py**.

what's interesting that when I run the **trt_ssd_async.py** and **trt_ssd.py** with Tensorflow0-1.12.2 jetpack-4.2.2, I get almost unit FPS, that's mean, The FPS is changed between 29-32 FPS, but with Tensorflow-1.15.0 jetpack 4.3, The FPS is changed between 13-23 FPS for **trt_ssd.py** and even **trt_ssd_aysnc.py**, I don't know why these changes are so great, As my input image the same.

**Comment by jkjung-avt** [comment]
1. "ERROR: nvcc not found" -> You just need to add /usr/local/cuda/bin" to your $PATH.  Reference: https://github.com/jkjung-avt/jetson_nano/issues/8#issuecomment-576001408

2. The difference in FPS is more related to TensorRT 5 vs. 6.  When you do inference with the optimized TensorRT engines, tensorflow is not used at all.

**Comment by PythonImageDeveloper** [comment]
1- I had added /usr/local/cuda/bin" to $PATH and didn't work again. I have to clean the if statement.

2- TensorRT 5 faster than TensorRT 6, I tested ssd models with both v5 , v6.
