### ISSUE TITLE
mtcnn detection poor fr heads pointing down

### ISSUE THREAD

**Issue by Tetsujinfr** [jkjung-avt/tensorrt_demos#440]
hi, is it a know fact that mtcnn is not robust to rotations? the landmarks are consistently detected for heads on top of bodies but if the heads are pointing down, then it is all over the place (either does not detect anything or put yes where mouth should be and vice versa).

Good detection exemple below:
![heads_standard_orientation](https://user-images.githubusercontent.com/29961693/123014467-3a485d00-d3be-11eb-8835-4e44c7b4e56b.jpg)

Poor examples below:
![heads_down1](https://user-images.githubusercontent.com/29961693/123014288-d1f97b80-d3bd-11eb-9a40-0cf2ce3d0eb9.jpg)

![heads_down2](https://user-images.githubusercontent.com/29961693/123014325-ed648680-d3bd-11eb-928a-c027f6ab10ab.jpg)

![heads_diag_low](https://user-images.githubusercontent.com/29961693/123014367-0836fb00-d3be-11eb-9762-4c6a5bee7988.jpg)

**Comment by jkjung-avt** [comment]
> hi, is it a know fact that mtcnn is not robust to rotations?

I did not train this model, neither did I verify such cases.  I think this is likely due to lack of upside-down faces in the training set.

**Comment by Tetsujinfr** [comment]
Ok thanks. Was curious to see if there was any experience with such scenarios which I did not expect tbh. Likely training set related indeed.
Closing
