### ISSUE TITLE
/usr/bin/ld: cannot find -lboost_python*-py3?

### ISSUE THREAD

**Issue by Sam-Fisher-20** [jkjung-avt/tensorrt_demos#442]
Hi - my python3.8 is in these places

python3: /usr/bin/python3 /usr/bin/python3.8-config /usr/bin/python3.8 /usr/lib/python3 /usr/lib/python3. 9 /usr/lib/python3.8 /etc/python3 /etc/python3.8 /usr/local/lib/python3.8 /usr/include/python3.8 /usr/sha re/python3 /usr/share/man/man1/python3.1.gz

I reinstalled python3.8 (thinking it would resolve -lboost error) 
Then deleted pycuda tree and ran install_pycuda script again. 
I got the error thrown at me again. 

/usr/bin/ld: cannot find -lboost_python*-py3?
collect2: error: ld returned 1 exit status
error: command 'x86_64-linux-gnu-g++' failed with exit status 1
make: *** [Makefile:6: all] Error 1

Any suggestion would be great. Thanks foryour help

**Comment by Sam-Fisher-20** [comment]
The real issue is I am not able to locate -lboost_python*-py3?

**Comment by jkjung-avt** [comment]
Could you do the following and see which .so files show up on your system?

```
$ ls /usr/lib/x86_64-linux-gnu/libboost_python*
```

**Comment by Sam-Fisher-20** [comment]
Hi Jung

There were libboost_python38.so files and I tried to create soft link with libboost_python38-py3.so- that did not work
I used ln -s XXXXXX.so XXXXXX.so

I sorted it by removing your tree and just sudo apt install pycuda directly.

Thank you

**Comment by jkjung-avt** [comment]
> I sorted it by removing your tree and just sudo apt install pycuda directly.

That should work.
