### ISSUE TITLE
I get a PyCUDA error when starting program at boot. 

### ISSUE THREAD

**Issue by MarritS** [jkjung-avt/tensorrt_demos#446]
When I run the program manually everything is fine, however when I attempt to start it at boot using crontab get the following error:

```
PyCUDA ERROR: The context stack was not empty upon module cleanup.

A context was still active when the contest stack was being cleaned up. At this point in our execution, CUDA may already have been deinitialized, so there is no way we can finish cleanly. The program will be aborted now. 
Use Context.pop() to avoid this problem
```

**Comment by jkjung-avt** [comment]
This is usually an error resulted from some other (prior) errors in the code.  Could you provide a full error log instead?

**Comment by jkjung-avt** [comment]
Closing due to no response.

**Comment by WackyHaker** [comment]
Hi, I am running into the same problem here. Did @MarritS manage to resolve this issue? I also have a log here, if @jkjung-avt can still assist me. 
![rdZ6bPYDdpA](https://user-images.githubusercontent.com/115628639/195320723-c63899ee-ef06-4146-9e1f-ca44cc83edc3.jpg)
