### ISSUE TITLE
How to modify the number of the anchors and Aspect ratio 

### ISSUE THREAD

**Issue by CHen-Hua-Luen** [jkjung-avt/tensorrt_demos#448]
Hi,thank you for your contribution,i want to know is it possible to modify the number of the anchors and aspect ratio? thanks.

**Comment by jkjung-avt** [comment]
Are you referring to YOLO models?

If so, the answer is yes.  My code would read anchor values from the cfg file and build TensorRT YOLO  engines accordingly.
