### ISSUE TITLE
yolov4-tiny custom weights issue

### ISSUE THREAD

**Issue by Myron1996** [jkjung-avt/tensorrt_demos#449]
Hi @jkjung-avt . I hope you are doing well. I am trying to convert my **`custom`** trained `**yolov4-tiny model**` but I am getting following error. I attached a **`cfg`** file. Can you help me with this ?

```
root@1bf3cb8ffb41:~/FastMOT/tensorrt_demos/yolo# python3 yolo_to_onnx.py -c 12 -m yolov4-tiny
Traceback (most recent call last):
  File "yolo_to_onnx.py", line 955, in <module>
    main()
  File "yolo_to_onnx.py", line 884, in main
    w, h = get_input_wh(args.model)
  File "/usr/src/app/FastMOT/tensorrt_demos/yolo/plugins.py", line 29, in get_input_wh
    h = w = int(yolo_dim)
ValueError: invalid literal for int() with base 10: 'tiny'

```
[yolov4-tiny.txt](https://github.com/jkjung-avt/tensorrt_demos/files/6821862/yolov4-tiny.txt)

**Comment by jkjung-avt** [comment]
Please `git pull` the latest code of this repo.  You should not encounter such a problem with the latest code.

By the way, you could refer to this blog post of mine: [TensorRT YOLO For Custom Trained Models (Updated)](https://jkjung-avt.github.io/trt-yolo-custom-updated/).
