### ISSUE TITLE
Half2 support requested on hardware without native FP16 support

### ISSUE THREAD

**Issue by Myron1996** [jkjung-avt/tensorrt_demos#450]
Hi @jkjung-avt . I am trying to convert the custom yolov4-tiny model in to trt and I am getting following warning. Can you please help me with this issue ? Thank you 

```
root@79b0ab1c4a79:~/tensorrt_demos/yolo# python3 onnx_to_tensorrt.py -m yolov4-tiny
Loading the ONNX file...
Adding yolo_layer plugins...
Building an engine.  This would take a while...
(Use "--verbose" or "-v" to enable verbose logging.)
[TensorRT] WARNING: Half2 support requested on hardware without native FP16 support, performance will be negatively affected.

```

**Comment by jkjung-avt** [comment]
> [TensorRT] WARNING: Half2 support requested on hardware without native FP16 support, performance will be negatively affected.

This means you are using a very old GPU which does not support FP16.  You'll have to build the TensorRT engine in FP32 mode.  For example, you could comment out the following lines in the source code:

https://github.com/jkjung-avt/tensorrt_demos/blob/fb2f075cc44a344062b31fa924bb9c4595ec7de4/yolo/onnx_to_tensorrt.py#L125

https://github.com/jkjung-avt/tensorrt_demos/blob/fb2f075cc44a344062b31fa924bb9c4595ec7de4/yolo/onnx_to_tensorrt.py#L137
