### ISSUE TITLE
No Detections with Yolov4-Tiny custom model 

### ISSUE THREAD

**Issue by Myron1996** [jkjung-avt/tensorrt_demos#451]
HI @jkjung-avt  . I hope you are doing well. I have a quick question 

I am running a custom trained  YOLOV4-Tiny Model with 12 classes. 

I managed to convert the model in to `**.trt** ` but When I am running an inference it is not showing  any detection's on video. Do you have any input on that ?

### Environment 
TensorRT Version: 7.1.3
Hardware  - NVIDIA Xavier 
Python Version (if applicable): 3.6.9

**Comment by jkjung-avt** [comment]
Have you verified your model with darknet?

Otherwise, check if this helps: https://github.com/jkjung-avt/tensorrt_demos/issues/434

**Comment by Myron1996** [comment]
HI @jkjung-avt , Thank you so much for above advice. apparently, reinstalling the docker image got everything working. :+1:
