### ISSUE TITLE
The class name of the custom object detection model converted to tensorrt has not changed.

### ISSUE THREAD

**Issue by Choikyungho9** [jkjung-avt/tensorrt_demos#453]
Hello, I have a custom weights file trained with yolov3.

When I first ran the weights file, the class name I trained on was displayed well. (my class name is 'pallet')
and filename is ' custom_yolov3-tiny '

However, after following the steps below, the class name is completely changed in the camera.
bycicle, person, etc..

```
$ cd ${HOME}/project/tensorrt_demos/yolo
$ ./download_yolo.sh
$ python3 yolo_to_onnx.py -m custom_yolov3-tiny
$ python3 onnx_to_tensorrt.py -m custom_yolov3-tiny
```

Why is the class name changing? please help what i am doing wrong

**Comment by jkjung-avt** [comment]
The source code is here: https://github.com/jkjung-avt/tensorrt_demos/blob/25adc48c43580d8a70f92032da3ac67c1a7bd70e/utils/yolo_classes.py#L99-L104

If the model has category_num=80 (default in the code), I assume it's a COCO model and use COCO object names.  You could modify object names in source code by yourself.  You could also refer to: https://github.com/jkjung-avt/tensorrt_demos/issues/233#issuecomment-697367143.
