### ISSUE TITLE
modnet work on x86_64 PC with NVIDIA GPU?

### ISSUE THREAD

**Issue by LuoYingzhao** [jkjung-avt/tensorrt_demos#458]
Thanks for your excellent work.
For demo7 MODNet, what modifications should be done, in order to work on x86_64 PC with NVIDIA GPU(or demo can directly work on x86)?

**Comment by jkjung-avt** [comment]
Sure, I have tested the code on a x86_64 PC.  It should just work.

**Comment by LuoYingzhao** [comment]
@jkjung-avt Thanks for your reply.I have run demo 7 on x86.
And another question. If I want to inference by C++, the engine build in step2 can be directly used（or need to do some modification to rebuild the engine）? Could you please give some suggestions?

**Comment by jkjung-avt** [comment]
> If I want to inference by C++, the engine build in step2 can be directly used?

Yes.
