### ISSUE TITLE
about openpose  TensorRT  demo accomplish？

### ISSUE THREAD

**Issue by zhanghongyong123456** [jkjung-avt/tensorrt_demos#460]
Do you have plans to implement openpose's TensorRT implementation

**Comment by jkjung-avt** [comment]
No, I don't have such a plan.

Maybe you could refer to NVIDIA's [NVIDIA-AI-IOT/trt_pose](https://github.com/NVIDIA-AI-IOT/trt_pose) sample.

**Comment by zhanghongyong123456** [comment]
> No, I don't have such a plan.
> 
> Maybe you could refer to NVIDIA's [NVIDIA-AI-IOT/trt_pose](https://github.com/NVIDIA-AI-IOT/trt_pose) sample.

1. yes，i find I tested the accuracy not admiration, not converted with caffemodel
2.For tensorrt ， Are there any recommended learning tutorials for newbies, in addition to official documents

**Comment by jkjung-avt** [comment]
> 2. For TensorRT, are there any recommended learning tutorials for newbies, in addition to official documents?

I don't have a good answer.  I myself do read the official [TensorRT Documentation](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html), [API Reference](https://docs.nvidia.com/deeplearning/tensorrt/api/index.html) and sample code included in the TensorRT releases.

But I'd say there's a lot of boiler plate code which you could just copy and do minor modifications.  For example, you could use my [onnx_to_tensorrt.py](https://github.com/jkjung-avt/tensorrt_demos/blob/master/yolo/onnx_to_tensorrt.py) as a basis of TensorRT engine building code.  And you could use the `TrtYOLO` class as a basis of inference code.

https://github.com/jkjung-avt/tensorrt_demos/blob/9dd56b3b8d841dcfc2e5d1868f4bd785a50cbe98/utils/yolo_with_plugins.py#L266

**Comment by zhanghongyong123456** [comment]
> > 1. For TensorRT, are there any recommended learning tutorials for newbies, in addition to official documents?
> 
> I don't have a good answer. I myself do read the official [TensorRT Documentation](https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html), [API Reference](https://docs.nvidia.com/deeplearning/tensorrt/api/index.html) and sample code included in the TensorRT releases.
> 
> But I'd say there's a lot of boiler plate code which you could just copy and do minor modifications. For example, you could use my [onnx_to_tensorrt.py](https://github.com/jkjung-avt/tensorrt_demos/blob/master/yolo/onnx_to_tensorrt.py) as a basis of TensorRT engine building code. And you could use the `TrtYOLO` class as a basis of inference code.
> 
> https://github.com/jkjung-avt/tensorrt_demos/blob/9dd56b3b8d841dcfc2e5d1868f4bd785a50cbe98/utils/yolo_with_plugins.py#L266

ok thank you for your reply， i will  learning  it ,Looking forward to your more project
