### ISSUE TITLE
Tracking Detections (Question)

### ISSUE THREAD

**Issue by DJT777** [jkjung-avt/tensorrt_demos#461]
Jkjung,

I last had an issue with getting detections in trt_yolo.py, and I was able to solve that by creating my own custom dataset.

Now that I am getting detections I was wondering if you know how tracking would be implemented in trt_yolo.py

**Comment by jkjung-avt** [comment]
https://github.com/jkjung-avt/tensorrt_demos/issues/407#issuecomment-839656018

**Comment by DJT777** [comment]
> [#407 (comment)](https://github.com/jkjung-avt/tensorrt_demos/issues/407#issuecomment-839656018)

Thanks, I didn't see this at first.
