### ISSUE TITLE
Yolov5 

### ISSUE THREAD

**Issue by abhigoku10** [jkjung-avt/tensorrt_demos#467]
@jkjung-avt  thanks for the code base do you have onnx_to_tensorrt.py for yolov5 ??

**Comment by jkjung-avt** [comment]
I have not tried it myself.  But if you manage to convert a YOLOv5 model to ONNX, "onnx_to_tensorrt.py" would likely work.

**Comment by abhigoku10** [comment]
@jkjung-avt  thanks for the response , will this work any version of the yolo since i see that in #56 your getting data from Darknetparser "from yolo_to_onnx import DarkNetParser, get_h_and_w"

**Comment by jkjung-avt** [comment]
Right.  My code was designed for DarkNet models.  If you are not using a DarkNet model, you'll have to modify the source code...

**Comment by abhigoku10** [comment]
@jkjung-avt  thanks for it !!! any future plans to make more independent of darknet module !!!

**Comment by jkjung-avt** [comment]
> any future plans to make more independent of darknet module !!!

I don't have such a plan now.

**Comment by abhigoku10** [comment]
@jkjung-avt  thankf or response
