### ISSUE TITLE
 Demo #7: modnet improves FPS 

### ISSUE THREAD

**Issue by hai8023** [jkjung-avt/tensorrt_demos#468]
Hello, is there any way to improve FPS? 4K video FPS can only reach about 6fps, and 2K video is about 20.

**Comment by jkjung-avt** [comment]
If your GPU supports INT8, you could try to build an INT8 TensorRT engine.  Otherwise, it might be possible to "prune" the MODNet model before optimization with TensorRT.

**Comment by hai8023** [comment]
Do you mean that you want to perform int8 quantization before reading the video?

**Comment by jkjung-avt** [comment]
> Do you mean that you want to perform int8 quantization before reading the video?

If you want to try that, you should build the TensorRT engine with INT8 enabled.  And yes, you'll have to implement an INT8 Calibrator for that to work.
