### ISSUE TITLE
darknet yolov4xmish vs converted tensorrt results- Too many false positive

### ISSUE THREAD

**Issue by akashAD98** [jkjung-avt/tensorrt_demos#473]
I have converted the darknet yolov4x-mish custom model into onnx & after tensorrt  (Tried both FP16 & F32),
The result of tensorrt model has too many FP & low detection.

i have tested both video frames on 0.7 confidence. Darknet is detecting more classes & less FP while tensorRT has more FP.
is there any way to solve this problem?  How can we improve precision ? @jkjung-avt 

this are the images 

Tensorrt with 0.7 confidence

![2825_img_ttensorrt_confi70](https://user-images.githubusercontent.com/62583018/131082343-fe2b0233-8a06-45de-9fcb-52824705de04.png)

Darknet with 0.7 confidence

![2825_img_darknet_confi70](https://user-images.githubusercontent.com/62583018/131082350-6d747faf-c694-44d0-a738-900ae61fe1e4.png)

**Comment by jkjung-avt** [comment]
This is generally very difficult to debug.  I could only refer you to information on the following link for now.  Try to check it with NVIDIA "polygraphy" if you're able to.

https://github.com/jkjung-avt/tensorrt_demos/issues/315

**Comment by akashAD98** [comment]
thanks for the reply, I'm a newbie in tensorRT, is there any way to learn tensorrt conversion for darknet??
In official tensorrt repo they have only a guide for PyTorch & TensorFlow .https://github.com/NVIDIA/TensorRT/tree/master/quickstart/IntroNotebooks, but I'm looking for darknet. How should i convert or understand basic of darknet-onnx-tensorrt.  plugins,batch size,kernal fusion .etc @jkjung-avt

**Comment by jkjung-avt** [comment]
https://github.com/jkjung-avt/tensorrt_demos/issues/460#issuecomment-897327938
