### ISSUE TITLE
[question]convert tensorflow models through UFF to TensorRT engines

### ISSUE THREAD

**Issue by MatheusCaltran** [jkjung-avt/tensorrt_demos#479]
hi, for me to use the SSD to TRT converter the model must be trained on a specific version of tensorflow or any tensorflow works (tensorflow 1.x and even tensorflow 2.x).

**Comment by jkjung-avt** [comment]
As stated in the README, the "Demo \#3: SSD" code in this repo was mainly tested against tensorflow-1.12.  I think tensorflow-1.8 up to 1.15 would all work.  But it would not work for tensorflow-2.x due to API changes.

**Comment by MatheusCaltran** [comment]
thanks
