### ISSUE TITLE
Compatibility of TensorRT optimized engine with deepstream-app

### ISSUE THREAD

**Issue by ahnjw72** [jkjung-avt/tensorrt_demos#48]
Thanks to the Demo #3: SSD, I've successfully made a TensorRT optimized 'engine' of SSD.
However, I got the following error message when I tried to use the engine with NVIDIA's deepstream-app (the deepstream-app can dedicate the TensorRT engine to be used in its pipeline) :

**deepstream-app: nvdsiplugin_ssd.cpp:72: FlattenConcat::FlattenConcat(const void*, size_t): Assertion `mConcatAxisID == 1 || mConcatAxisID == 2 || mConcatAxisID == 3' failed.
Aborted (core dumped)**

I'm not familiar with the deepstream-app plugin structure and hope that any expert can explain what is the main cause of this problem and what I should do to use any TensorRT optimized engine in the deepstream pipeline.
(Before, I expected that the deepstream can perform inference by a user dedicated TensorRT optimized engine without any coding or plugin library building.. )

**Comment by jkjung-avt** [comment]
@ahnjw72  Thanks for your comment.  But I'm sorry.  I don't currently use DeepStream SDK, and I don't have the time to look into this.  I suggest you to post the issue onto [NVIDIA Developer Forum](https://devtalk.nvidia.com/default/board/209/deepstream-sdk/) and seek help from NVIDIA.
