### ISSUE TITLE
GStreamer issue: using an HTTP streaming as input

### ISSUE THREAD

**Issue by BenjaminQU259** [jkjung-avt/tensorrt_demos#480]
Hi,

I was working with [Demo #5: YOLOv4](https://github.com/jkjung-avt/tensorrt_demos#yolov4) on my Jetson AGX Xavier, and it worked flawlessly when I used an MP4 video file as input.

But now, I need to use HTTP streaming as the input. So I tried the `open_cam_gstr`, and passed the argument as:
<pre>python3 trt_yolo.py --gstr 'souphttpsrc location=http://{username}:{passwd}@{IP_address}:{port}/stream.mjpg ! jpegdec ! xvimagesink' -m {model}</pre>

Then I got this error:
<pre>[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (801) open OpenCV | GStreamer warning: cannot find appsink in manual pipeline
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
WARNING:root:Camera: starting while cap is not opened!
ERROR: failed to open camera!</pre>

I'm not sure how this error occurred, but I went ahead and tried opening the streaming directly with GStreamer:
<pre>gst-launch-1.0 souphttpsrc location=http://{username}:{passwd}@{IP_address}:{port}/stream.mjpg ! jpegdec ! xvimagesink</pre>
And it worked. I'm sure the steaming address is correct.

I'm new to this and I don't know where the problem is.

Any help would be appreciated.

**Comment by jkjung-avt** [comment]
Try this instead:

> python3 trt_yolo.py --gstr 'souphttpsrc location=http://{username}:{passwd}@{IP_address}:{port}/stream.mjpg ! videoconvert ! appsink' -m {model}

**Comment by BenjaminQU259** [comment]
Thank you for the quick reply. So I tried:
> python3 trt_yolo.py --gstr 'souphttpsrc location=http://{username}:{passwd}@{IP_address}:{port}/stream.mjpg ! videoconvert ! appsink' -m {model}

And now I got this:

<pre>[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (1757) handleMessage OpenCV | GStreamer warning: Embedded video playback halted; module souphttpsrc0 reported: Internal data stream error.
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (886) open OpenCV | GStreamer warning: unable to start pipeline
[ WARN:0] global /home/nvidia/host/build_opencv/nv_opencv/modules/videoio/src/cap_gstreamer.cpp (480) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
WARNING:root:Camera: starting while cap is not opened!
ERROR: failed to open camera!</pre>

**Comment by jkjung-avt** [comment]
Sorry, my bad.  I missed the jpeg decoder in the pipeline.

> python3 trt_yolo.py --gstr 'souphttpsrc location=http://{username}:{passwd}@{IP_address}:{port}/stream.mjpg ! jpegdec ! videoconvert ! appsink' -m {model}

**Comment by BenjaminQU259** [comment]
OK it worked:
> python3 trt_yolo.py --gstr 'souphttpsrc location=http://{username}:{passwd}@{IP_address}:{port}/stream.mjpg ! jpegdec ! videoconvert ! appsink' -m {model}

Fantastic! Thank you very much!
