### ISSUE TITLE
Op registered for Upsample is deprecated in domain_version of 15

### ISSUE THREAD

**Issue by marshallia** [jkjung-avt/tensorrt_demos#486]
![image](https://user-images.githubusercontent.com/12694360/136504025-37821db0-d894-4284-82dc-b658295f59c2.png)\
Hi,,
I am trying to convert my Darknet YOLOV3 tiny weight to Onnx but got this error. The model input size is 416 with 9 classes, use filter = 42 from (class+5)*3 .

**Comment by marshallia** [comment]
I think I found my problem, I install it on my PC instead of my Jetson Xavier therefore it keep failing. It work well now. Thank you very much!

**Comment by jkjung-avt** [comment]
@akashAD98 

> Not able to install onnx 1.4.1

Maybe you could try `pip3 install pybind11` before onnx==1.4.1...

**Comment by jkjung-avt** [comment]
Refer to: https://github.com/jkjung-avt/tensorrt_demos/issues/539#issuecomment-1119218462

The code has been updated to use onnx==1.9.0 now.
