### ISSUE TITLE
Using mtcnn for video stream can only detect 1 face?

### ISSUE THREAD

**Issue by edwardchang0112** [jkjung-avt/tensorrt_demos#490]
I just tried to use mtcnn for video stream, which is a repeated video, for the first time mtcnn can succefully detect multiple faces at a moment, but for the next round at same frame, it cannot detect more than 1 face at a moment. Any idea on this issue?

**Comment by edwardchang0112-nctu** [comment]
> I don't remember if I've verified it with TensorRT 6. So I don't know.
> 
> Another alternative would be to use TensorRT 8 (JetPack-4.6).

Hi @jkjung-avt ,
I have already flashed my NX to JetPack-4.6 with TensorRT 8, and after installing the Tensorflow according to NVIDIA's website https://docs.nvidia.com/deeplearning/frameworks/install-tf-jetson-platform/index.html.

When I tried to ./build_engine.sh in /ssd...

1. If I install Tensorflow -1.15.5+nv21.7, will got error as follows
```
[TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +331, GPU +0, now: CPU 495, GPU 6578 (MiB)
Traceback (most recent call last):
  File "build_engine.py", line 304, in <module>
    main()
  File "build_engine.py", line 289, in main
    builder.max_workspace_size = 1 << 28
AttributeError: 'tensorrt.tensorrt.Builder' object has no attribute 'max_workspace_size'
```
2. If I install Tensorflow-2.5.0+nv21.7, will got error as follows
```
+ for model in ssd_mobilenet_v1_coco ssd_mobilenet_v1_egohands ssd_mobilenet_v2_coco ssd_mobilenet_v2_egohands
+ python3 build_engine.py ssd_mobilenet_v1_coco
./build_engines.sh: line 5: 15229 Illegal instruction     (core dumped) python3 build_engine.py ${model}
```
How to know all the correct versions of requirements libraries(numpy...) and frameworks(opencv...) for running with TensorRT 8 to make this repo run correctly?

**Comment by jkjung-avt** [comment]
I have not been updating the SSD demo code since TensorFlow 2.x came out.  I think some code modification would be needed for it to work with modern versions of TensorRT and TensorFlow.

**Comment by edwardchang0112-nctu** [comment]
> I have not been updating the SSD demo code since TensorFlow 2.x came out. I think some code modification would be needed for it to work with modern versions of TensorRT and TensorFlow.

Is that possible to use Tensorflow -1.15.5+nv21.7, but resolve the issue?

**Comment by jkjung-avt** [comment]
> 1. If I install Tensorflow -1.15.5+nv21.7, will got error as follows
> ```
> [TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +331, GPU +0, now: CPU 495, GPU 6578 (MiB)
> Traceback (most recent call last):
>   File "build_engine.py", line 304, in <module>
>     main()
>   File "build_engine.py", line 289, in main
>     builder.max_workspace_size = 1 << 28
> AttributeError: 'tensorrt.tensorrt.Builder' object has no attribute 'max_workspace_size'
> ```

This particular problem is due to API change between TensorRT 7+ and earlier versions.  You need to modify the code to use "builder config" and call `engine = builder.b](uild_engine(network, config)` instead.  You could refer to [yolo/onnx_to_tensorrt.py](https://github.com/jkjung-avt/tensorrt_demos/blob/master/yolo/onnx_to_tensorrt.py) for how to do that.

**Comment by edwardchang0112-nctu** [comment]
> > 1. If I install Tensorflow -1.15.5+nv21.7, will got error as follows
> > 
> > ```
> > [TensorRT] INFO: [MemUsageChange] Init CUDA: CPU +331, GPU +0, now: CPU 495, GPU 6578 (MiB)
> > Traceback (most recent call last):
> >   File "build_engine.py", line 304, in <module>
> >     main()
> >   File "build_engine.py", line 289, in main
> >     builder.max_workspace_size = 1 << 28
> > AttributeError: 'tensorrt.tensorrt.Builder' object has no attribute 'max_workspace_size'
> > ```
> 
> This particular problem is due to API change between TensorRT 7+ and earlier versions. You need to modify the code to use "builder config" and call `engine = builder.b](uild_engine(network, config)` instead. You could refer to [yolo/onnx_to_tensorrt.py](https://github.com/jkjung-avt/tensorrt_demos/blob/master/yolo/onnx_to_tensorrt.py) for how to do that.

Could you explain more? how to modify the code?

**Comment by edwardchang0112** [comment]
> > Could you explain more? how to modify the code?
> 
> https://github.com/jkjung-avt/tensorrt_demos/blob/f53b5ae9b004489463a407d8e9b230f39230d051/yolo/onnx_to_tensorrt.py#L145-L170

This is for Yolo, how about the modification for ssd? since I am now trying to use ssdmobilev2, but in ./build_engine.sh got the error.

**Comment by jkjung-avt** [comment]
The TensorRT engine building code should be the same for UFF-SSD and ONNX-YOLO (and all other models).  If you don't use INT8 and DLA, you could remove the relevant code.  Otherwise, you just need to pay attention to setting the correct shape (NCHW) in the optimization profile.

**Comment by edwardchang0112** [comment]
> The TensorRT engine building code should be the same for UFF-SSD and ONNX-YOLO (and all other models). If you don't use INT8 and DLA, you could remove the relevant code. Otherwise, you just need to pay attention to setting the correct shape (NCHW) in the optimization profile.

How to know whether I use INT8 or DLA? And still not really sure how to modify the code... Is that possible you use the code in /ssd/build_engine.sh to have a explaination? Where to modify? How to modify? Thanks in advance!

**Comment by jkjung-avt** [comment]
Sorry I cannot help further.  You need to understand the code and implement the modification by yourself.

**Comment by sachinkmohan** [comment]
> > > Could you explain more? how to modify the code?
> > 
> > 
> > https://github.com/jkjung-avt/tensorrt_demos/blob/f53b5ae9b004489463a407d8e9b230f39230d051/yolo/onnx_to_tensorrt.py#L145-L170
> 
> This is for Yolo, how about the modification for ssd? since I am now trying to use ssdmobilev2, but in ./build_engine.sh got the error.

Thanks @jkjung-avt ! for solving this! It helped me do the changes accordingly.

As per @jkjung-avt's comment, I have modified the changes and it now works in Jetpack 4.6. I tested this with TF 1.15. Please refer the below on the comparison of the changes.
https://github.com/sachinkmohan/tensorrt_demos_jp46/pull/1/files

Also please refer the `requirements.txt` file if required on the packages I used.

[ssd/requirements.txt](https://github.com/sachinkmohan/tensorrt_demos_jp46/blob/dca1094ff773449a1addd5cf12a4ab6ee683ccd1/ssd/requirements.txt)
