### ISSUE TITLE
AttributeError: 'Nonetype' object has no attibute 'serialize'

### ISSUE THREAD

**Issue by sabaridsn** [jkjung-avt/tensorrt_demos#495]
I am trying to convert the custom tensorflow SSD_MobileNet_V3 to TensorRT engine. I am getting the above error.

**Comment by jkjung-avt** [comment]
I myself have spent some time trying to convert the pre-trained ssd_mobilenet_v3 to TensorRT, but did not get it to work.  I left the work in progress in the [ssd_mobilenet_v3](https://github.com/jkjung-avt/tensorrt_demos/tree/ssd_mobilenet_v3) branch.  I don't have a plan to look into this further....

**Comment by sabaridsn** [comment]
oh! :(
