### ISSUE TITLE
Support for different number of classes and yolov4-px models

### ISSUE THREAD

**Issue by lpkoh** [jkjung-avt/tensorrt_demos#497]
Hi,

Can I check if support for "custom models" means that you can convert darknet yolo models to onnx that differ not only in **image dimension (e.g. 640x 640 -> 640x320)**, but also **different number of classes**? Thanks!

**Comment by jkjung-avt** [comment]
Yes.

**Comment by lpkoh** [comment]
Holy shit thank you man
