### ISSUE TITLE
Define New Activation Layer

### ISSUE THREAD

**Issue by PythonImageDeveloper** [jkjung-avt/tensorrt_demos#50]
Hi,
I want to use mobilenet_v3 module in my network, and in this module is used HardSwitch activation such this:

```
def relu6(x):
    return tf.nn.relu(x)

def hard_swish(x):
    return x * tf.nn.relu(x + 3.0) / 6.0

def return_activation(x, nl):
    if nl == 'HS':
        x = Activation(hard_swish)(x)
    if nl == 'RE':
        x = Activation(relu6)(x)
    return x
```

If I want to convert to UFF and TensorRT, I should use a plugin for these layers? If so, How do I do for writing a custom plugin?

**Comment by jkjung-avt** [comment]
All operations in your code snippet, i.e. "relu", "add" and "mul", should be supported by TensorRT already.  I think you don't need to create plugin's for the activation functions.
