### ISSUE TITLE
Optimising Mask-RCNN for NVIDIA Jetson devices 

### ISSUE THREAD

**Issue by pra-dan** [jkjung-avt/tensorrt_demos#500]
Hi, I wanted to know if you have ever tried to optimise the mrcnn model for Jetson Xavier. I see it to be tricky.

**Comment by jkjung-avt** [comment]
I myself have not tried it.

NVIDIA does provide a sample for how to do that though: [7.6. Object Detection And Instance Segmentation With A TensorFlow Mask R-CNN Network](https://docs.nvidia.com/deeplearning/tensorrt/sample-support-guide/index.html#sampleuffmaskrcnn).

**Comment by pra-dan** [comment]
I have used this one and it works well. But integration into DeepStream or any other API-based application is difficult
