### ISSUE TITLE
yolov4-csp training with custom-dataset

### ISSUE THREAD

**Issue by Wooks-git** [jkjung-avt/tensorrt_demos#501]
Hi, could you share the link that you trained yolov4-csp?
I want to train yolov4-csp256 with my custom dataset, but I don't know exactly if this link is right.

https://github.com/WongKinYiu/ScaledYOLOv4/tree/yolov4-csp

**Comment by jkjung-avt** [comment]
I only used the pre-trained DarkNet yolov4-csp: https://github.com/AlexeyAB/darknet/blob/master/cfg/yolov4-csp.cfg

**Comment by Wooks-git** [comment]
Then, if I want to learn yolov4-csp-256, do I only need to adjust the width height?

**Comment by jkjung-avt** [comment]
> Then, if I want to learn yolov4-csp-256, do I only need to adjust the width height?

Yes, I think so.

**Comment by Wooks-git** [comment]
Hi Thank you for reply!

I finished my yolov4-csp-256 model. How do i modify yolo_to_onnx.py and onnx_to_trt.py?

trained classes : 3 (face, phone, cigar)

**Comment by jkjung-avt** [comment]
1. "yolo_to_onnx.py" and "onnx_to_trt.py" should just work.  No need to modify them.
2. Refer to https://github.com/jkjung-avt/tensorrt_demos/issues/421 for how to modify the code to display your own custom class names at inference time.

**Comment by Wooks-git** [comment]
ok thanks a lot!
i'll try it
