### ISSUE TITLE
Python >3.6 with jetson nano

### ISSUE THREAD

**Issue by C-monC** [jkjung-avt/tensorrt_demos#507]
Hi,

Is it possible to run these examples with python3.8 on a jetson nano?
It doesn't seem possible to build tensorrt for jetson products. Is it possible to generate only the python bindings from the preinstalled tensorrt from JetPack?

**Comment by jkjung-avt** [comment]
NVIDIA has open-sourced TensorRT python binding earlier this year.  You could probably build the "tensorrt" module for python3.8 by yourself.  (I myself have not tried it.)

Please refer to: https://github.com/NVIDIA/TensorRT/tree/21.02/python

**Comment by C-monC** [comment]
Thank you. Seeing as python3.6 is EOL in less than 2 months it's critical for the long term (and async support).
