### ISSUE TITLE
Correct Syntax for passing ina cls camera stream.?

### ISSUE THREAD

**Issue by sjdolley** [jkjung-avt/tensorrt_demos#513]
Hi, was following your examples on your blog with success on my jetson nano-2GB with the yolov4 models using a usb camera. I now wish to use a cls camera on /dev/video0 that i can stream with
gst-launch-1.0 nvarguscamerasrc ! nvoverlaysink
I am wondering the correct syntax to run inference on the stream with trt_yolo.py
something like
python3 trt_yolo.py --gstr (this pat here i get wrong) -m yolov4-tiny-416
for usb i used
python3 trt_yolo.py --usb 0 -m yolov4-tiny-416 and it worked well?

Thanks for any help you can give and sorry for the newb question, but i am quite new to all this.

**Comment by jkjung-avt** [comment]
You can try "--onboard 0" first.  If that does not work, try to tweak the GStreamer pipeline in the code:

https://github.com/jkjung-avt/tensorrt_demos/blob/f53b5ae9b004489463a407d8e9b230f39230d051/utils/camera.py#L114-L121
