### ISSUE TITLE
mtcnn Multi process operation error

### ISSUE THREAD

**Issue by momohuangsha** [jkjung-avt/tensorrt_demos#520]
[TensorRT] ERROR: ../rtSafe/cuda/reformat.cu (925) - Cuda Error in NCHWToNCHHW2: 400 (invalid resource handle)
[TensorRT] ERROR: FAILED_EXECUTION: std::exception
Hope to give advice. thanks!

**Comment by jkjung-avt** [comment]
Did you create TrtMtcnn objects separately inside each individual process which does inference with the specific context (object instance)?

**Comment by jkjung-avt** [comment]
Close due to no response.
