### ISSUE TITLE
ERROR: failed to build the TensorRT engine!

### ISSUE THREAD

**Issue by ddinhtuann** [jkjung-avt/tensorrt_demos#522]
I try to convert onnx to tensorrt without int8 and dla_core but got this error bellow,would some one help me up?![image](https://user-images.githubusercontent.com/82692115/148016023-f09cb0ca-725f-4199-8e21-62bb8c8e8a44.png)

**Comment by jkjung-avt** [comment]
I myself have never encountered this error before.

This probably does not help too much.  But anyway, this is what TensorRT header file ("NvInferRuntimeCommon.h") says about Error Code 2:

```
    //!
    //! A non-recoverable TensorRT error occurred. TensorRT is in an invalid internal state when this error is
    //! emitted and any further calls to TensorRT will result in undefined behavior.
    //!
    kINTERNAL_ERROR = 2,
```

**Comment by ddinhtuann** [comment]
Thanks, I found why the error caused: DLA_core was wrong type and I fixed it. I finished built the tensort engine but when I run trt_yolo.py through vscode remote ssh, my jetson power off even I set maxn nvpmodel, jetson_clocks. I dont show the frames with cv2_imshow(), i just print the fps and write those frames to .avi file. Do you have any ideal?

**Comment by jkjung-avt** [comment]
Are you using a proper AC-DC adapter to power the Jetson system?

**Comment by ddinhtuann** [comment]
Yes, I am using a AC-DC adapter to supply 5V-4A via Power Jack
