### ISSUE TITLE
Error opening engine file with ./trtexec

### ISSUE THREAD

**Issue by lpkoh** [jkjung-avt/tensorrt_demos#528]
Hi, I am trying to test the speed of the trt models.

I ran yolo_to_onnx.py and onnx_to_tensorrt.py and successfully ran eval_yolo.py and saw the fps and bounding boxes.

However, I ran ./trtexec --loadEngine=<file> + other settings for inference phase (reference: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#trtexec-serialized-timing-cache) to obtain a different fps estimate and I got "Error opening engine file".

![image](https://user-images.githubusercontent.com/48631399/150660917-1f6bc450-91e8-40a4-8567-4957157a8a1e.png)

Likewise, when I use the trt files I obtain from converting darknet models to onnx using tianxiaomo's directory, then convert those to trt using ./trtexec, those models are not usable in this repo.

![image](https://user-images.githubusercontent.com/48631399/150660906-3a74b1c4-416b-4459-a058-f2b6efa7c60b.png)

Could you clarify on this issue?

Also a separate clarification, is the conversion in onnx_to_trt by default fp16?

**Comment by jkjung-avt** [comment]
@lpkoh  The TensorRT YOLO engines built with this repo would contain the "yolo_layer" plugin.  So you'll have to call trtexec with something like the following. 

```
$ ./trtexec --loadEngine=yolo/yolov4-tiny.trt --plugins=plugins/libyolo_layer.so
```
