### ISSUE TITLE
The problem of yolov3_onnx

### ISSUE THREAD

**Issue by brian208579** [jkjung-avt/tensorrt_demos#53]
Followed the Demo #4: YOLOv3
when i execute this command at step3
python3 yolov3_to_onnx.py --model yolov3-tiny-416
I got the error below figure
![problem_1](https://user-images.githubusercontent.com/43407888/73626386-a6b8a400-4683-11ea-885f-2c326c68729d.png)
I already update my protobuf to a recent version
Do you have any suggestions ?

**Comment by jkjung-avt** [comment]
Are you using onnx==1.4.1?

**Comment by brian208579** [comment]
@jkjung-avt yes, i do .

**Comment by jkjung-avt** [comment]
Reference: https://github.com/onnx/onnx/issues/2534

I was using protobuf-3.8.0, and did not see this problem.  Could you try the same version?

**Comment by brian208579** [comment]
@jkjung-avt 
sorry , i'm late for reply .
I try the protobuf-3.8.0 version and using sudo pip3 install protobuf==3.8.0 then it slove my problem
appreciate
