### ISSUE TITLE
Save video on the YOLO models?

### ISSUE THREAD

**Issue by lolcocks123** [jkjung-avt/tensorrt_demos#532]
Hello,

I was wondering if it is possible to save the videos on the YOLO models like the `--create_video` parameter on the MODNet demo?

Regards,
Lolcocks

**Comment by jkjung-avt** [comment]
Yes, you could run [trt_yolo_cv.py](https://github.com/jkjung-avt/tensorrt_demos/blob/master/trt_yolo_cv.py).

**Comment by lolcocks123** [comment]
> Yes, you could run [trt_yolo_cv.py](https://github.com/jkjung-avt/tensorrt_demos/blob/master/trt_yolo_cv.py).

Thanks! Didn't know this existed. :)
