### ISSUE TITLE
Is there a way to use yolo to tensorrt with Keras ?

### ISSUE THREAD

**Issue by zohaibjan** [jkjung-avt/tensorrt_demos#534]
First of all I am fairly new to the field so please bare with my questions if they seem trivial. The implementation of YoloV4 I am using is based on keras from this [repo ](https://github.com/taipingeric/yolo-v4-tf.keras). Because of licensing I cannot use Darknet based implementation. 

I would like to convert my trained model to tensorRT and infer from it. Is there a way I can utilise yolo to onnx and onnx to tensort that you have implemented ?

**Comment by jkjung-avt** [comment]
This is not guaranteed to work.  But you might try to convert your Keras model to ONNX first, then use "onnx_to_tensorrt.py" to optimize it into a TensorRT engine.
