### ISSUE TITLE
Convert onnx-tensorRT yolov5s 

### ISSUE THREAD

**Issue by dFuong** [jkjung-avt/tensorrt_demos#543]
I need to convert yolov5s model with image-size=640x640

Someone can help me?

**Comment by jkjung-avt** [comment]
Are you trying to convert a DarkNet model or a PyTorch model or else?  The code ("yolo_to_onnx.py") in this repo only works for DarkNet models.

**Comment by dFuong** [comment]
thanks your response, I understand. I'll try.
