### ISSUE TITLE
在onnx转tensorrt时候报错，

### ISSUE THREAD

**Issue by wangyu96-art** [jkjung-avt/tensorrt_demos#546]
在onnx转tensorrt时候报错，
cuda failure in file 'yolo_layer.cu' line 51:35
Aborted (core dumped)
请求大佬援助

**Comment by wangyu96-art** [comment]
Using a custom yolov3 model after cropping

**Comment by jkjung-avt** [comment]
Duplicate as https://github.com/jkjung-avt/tensorrt_demos/issues/547
