### ISSUE TITLE
Error in onnx to tensorrt. cuda failure in file 'yolo_layer.cu' line 51:35 Aborted (core dumped) Request assistance from the big guys

### ISSUE THREAD

**Issue by wangyu96-art** [jkjung-avt/tensorrt_demos#547]
Error in onnx to tensorrt.
cuda failure in file 'yolo_layer.cu' line 51:35
Aborted (core dumped)
Request assistance from the big guys

**Comment by wangyu96-art** [comment]
Using a custom yolov3 model after cropping

**Comment by wangyu96-art** [comment]
CHECK(cudaMalloc(&mAnchors, MAX_ANCHORS * 2 * sizeof(float)));

**Comment by jkjung-avt** [comment]
Please provide your cfg file.  I will take a look.

**Comment by wangyu96-art** [comment]
[converted.zip](https://github.com/jkjung-avt/tensorrt_demos/files/8638228/converted.zip)

**Comment by jkjung-avt** [comment]
Your cfg file looks OK to me.

Failure to execute this line of code means the program cannot allocate memory on the GPU.

```C
CHECK(cudaMalloc(&mAnchors, MAX_ANCHORS * 2 * sizeof(float)));
```

Which GPU are you using?  Do you have multiple GPUs on the system?  If so, try to set, say, `CUDA_VISIBLE_DEVICES=0` (environment variable) to see if it helps.

**Comment by wangyu96-art** [comment]
I'm using a Jetson nano development board, I'll try your help first, thanks.

**Comment by jkjung-avt** [comment]
There should be only 1 GPU on your Jetson DevKit...

I wonder whether there's a hardware problem on your Jetson, or maybe most of the system memories have been occupied by other programs.
