### ISSUE TITLE
Close the output window

### ISSUE THREAD

**Issue by jacksonchen1998** [jkjung-avt/tensorrt_demos#564]
Can the program close the ouput window while running `trt_yolo.py` for image detection ?
I think it may improve the fps for displaying output image on the window.

**Comment by jkjung-avt** [comment]
Sure.  You could remove the code which does image drawing and displaying.  And you'll need add code to print FPS values to be able to check it.

https://github.com/jkjung-avt/tensorrt_demos/blob/a061e44a82e1ca097f57e5a32f20daf5bebe7ade/trt_yolo.py#L70-L72
