### ISSUE TITLE
Multiple Bounding Boxes

### ISSUE THREAD

**Issue by soukaina11111** [jkjung-avt/tensorrt_demos#582]
hi @jkjung-avt, I’ve trained a model for the detection of person and hat and then convert it, but it is giving multiple bounding box for one detection especially for the class hat like the figure below. 

![example](https://user-images.githubusercontent.com/110026231/191260219-b4855b52-22e7-4f1b-9e54-a4c10f3b1b46.png)

NB: I'm using yolov4-csp-swish 640 map 89%, and when I do the inference with opencv I don’t have that problem. 

Any idea how to solve it?

Thank you in advance.

**Comment by jkjung-avt** [comment]
What are CLS0 (class 0) and CLS1 (class 1) of your custom model?

**Comment by soukaina11111** [comment]
class 0 : person, class 1: Hat.

**Comment by jkjung-avt** [comment]
How would you label (ground truth) this picture then?

Or, what is the inference result with OpenCV?

**Comment by soukaina11111** [comment]
this is the result i got with opencv 
![test](https://user-images.githubusercontent.com/110026231/191691671-ac3ae790-54c3-42f7-8ea3-51f482df71d6.png)

**Comment by jkjung-avt** [comment]
Thanks for reporting this issue.  But currently I don't have an idea what the root cause is...

**Comment by soukaina11111** [comment]
okay thanks for your response.
