### ISSUE TITLE
Mtcnn accuracy problem

### ISSUE THREAD

**Issue by SaddamBInSyed** [jkjung-avt/tensorrt_demos#59]
Thanks for your work.

I have carefully followed your build instructions and when I run the TensorRT mtcnn face detector on my jetson nano, I am getting low accuracy as like below
code detecting my hand as a face (continuously for some seconds ).

please advise.

![image](https://user-images.githubusercontent.com/10062672/74310061-b623a580-4d85-11ea-8e8b-27facf6748fe.png)

**Comment by jkjung-avt** [comment]
I think my TensorRT MTCNN result should be very close to the original Caffe model.

I did not train the original Caffe MTCNN model by myself.  If you'd like to improve its recall/precision, please look into how to re-train or fine tune it.

**Comment by julayelei** [comment]
Hello, Saddam. You can also change values of MINSIZE for faces detected. Sometimes, some objects "look" like a face. By default, it uses 40 minzise in utils/mtcnn. Try changing it to a higher minsize!

**Comment by SaddamBInSyed** [comment]
@jkjung-avt 
thanks for your advice

seems it works fine when I change the minsize from 40 to 100 pixels.

thank you.

**Comment by jkjung-avt** [comment]
Thanks to @julayelei
