### ISSUE TITLE
Batch Processed Image Inference

### ISSUE THREAD

**Issue by loginabhay** [jkjung-avt/tensorrt_demos#591]
Hi i was able to run the batch inference for yolov4 trt model but after getting the output how to identify which output belongs to which image from the created batch of frames currently getting the output classes as this for 4 images.

>>>>>>>>Classes:  [0. 1. 2. 2. 6. 6. 6. 7. 7. 7. 7.]

How to map these to the images. Kindly help me here

**Comment by jkjung-avt** [comment]
Please refer to https://github.com/jkjung-avt/tensorrt_demos/issues/306.

Basically, you need to separate inference results for image before you do NMS.

**Comment by loginabhay** [comment]
@jkjung-avt Thanks for the quick response and amazing work i was able to solve that.
