### ISSUE TITLE
Xavier onnx to TensorRT error

### ISSUE THREAD

**Issue by kaikkk123** [jkjung-avt/tensorrt_demos#600]
Hello! I encountered the following error while running onnx to tensorRT on Xavier 

[TensorRT] WARNING: TensorRT was linked against cuDNN 8.0.2 but loaded cuDNN 8.0.0
[TensorRT] ERROR: ../builder/cudnnBuilderWeightConverters.cpp (541) - Misc Error in operator(): 1 (Weights are outside of fp16 range. A possible fix is to retrain the model with regularization to bring the magnitude of the weights down.)
[TensorRT] ERROR: ../builder/cudnnBuilderWeightConverters.cpp (541) - Misc Error in operator(): 1 (Weights are outside of fp16 range. A possible fix is to retrain the model with regularization to bring the magnitude of the weights down.)
ERROR: failed to build the TensorRT engine!

I would like to ask if you have relevant experience, and if retraining is the only solution?
Could this be related to my TensorRT or cuDNN version?
 TensorRT version : 7.2.0
 cuDNN  version : 8.0.0

**Comment by jkjung-avt** [comment]
https://github.com/jkjung-avt/tensorrt_demos/issues/161#issuecomment-662473343
