### ISSUE TITLE
more Facial landmark in mtcnn

### ISSUE THREAD

**Issue by SaddamBInSyed** [jkjung-avt/tensorrt_demos#62]
@jkjung-avt ,
Thanks for your work.

how to get 68 points facial landmark (as like dlib) using MTCNN.
currently, it's giving only 5 facial points.
Since I want to do head pose estimation I am need of the other facial points

please advise.

**Comment by jkjung-avt** [comment]
MTCNN is designed and trained with only 5 facial landmarks.  If you want to do 68 points, you need to train your own model.

Reference: [official web site of MTCNN](https://kpzhang93.github.io/MTCNN_face_detection_alignment/)

![image](https://user-images.githubusercontent.com/19985967/74849207-6b042680-5373-11ea-87f6-b65ea28df4cc.png)

**Comment by SaddamBInSyed** [comment]
thanks for the information

**Comment by SaddamBInSyed** [comment]
@jkjung-avt ,

how to extract/crop left_eye and right_eye image from mtcnn facial landmark.
I want to find face drowsiness and other stuff.

please advise.

**Comment by jkjung-avt** [comment]
The landmarks output by MTCNN already include left and right eyes.  I think you could use those to extract image crops of the eyes and maybe train a classifier to do drowsiness detection.
