### ISSUE TITLE
Cask Error (Cask Convolution execution) when using with Flask

### ISSUE THREAD

**Issue by bikramb98** [jkjung-avt/tensorrt_demos#68]
Hi, 
I am running into multiple Cask errors when using the Yolov3 TensorRT with Flask. It works fine by itself, but gives `[TensorRT] ERROR: cuda/caskConvolutionLayer.cpp (256) - Cask Error in CheckCaskExecError: 7`

I have tried the suggestion posted below, but that didn't work: 

```
device = cuda.Device(0)
context = device.make_context()

// TRT engine create_execution_context()
// do inferencing

context.pop()
del context
```

Please suggest how to go about solving this. It might be a problem specifically to Yolo

**Comment by jkjung-avt** [comment]
You are going in the right direction.  You just need to figure out how Flask creates threads.  And make sure you "make cuda context", "create tensorrt execution context" and "do inferencing" all in the same thread.

**Comment by jkjung-avt** [comment]
Closing this issue since there's no update for over a month.

**Comment by jkjung-avt** [comment]
Please find a solution here: https://github.com/jkjung-avt/tensorrt_demos/issues/213#issuecomment-691826122.  Be sure to `git pull` the latest code from this repo.

In addition, @Papageno2 is kind enough to share full working source code here: https://github.com/jkjung-avt/tensorrt_demos/issues/213#issuecomment-691940559.  I think it would help.
