### ISSUE TITLE
Why meet issues after remove "key = cv2.waitKey(1)"

### ISSUE THREAD

**Issue by sudo-wang** [jkjung-avt/tensorrt_demos#77]
Hi, @jkjung-avt 
Thanks for your work! It helps me a lot. You are very kind! 
I want to achieve that when the video detection is finished, stop the loop and exit directly. Instead of going through the loop until the 'ESC' key is pressed.
So I calculated the total number of frames in the video file, and remove "key = cv2.waitKey(1)". Just like this:
('total' is the total number of frames in the video file; 
'frameIndex' is a variable of +1 after each loop detection )
![image](https://user-images.githubusercontent.com/30141622/78144487-3b603800-7462-11ea-8e9b-cd3186f33750.png)
In the end, I run python trt_ssd_async.py --model ssd_mobilenet_v1_coco --file --filename ./examples/test_video/IMG_8706.MP4
But **the log is right, the detected video was not show.**
![image](https://user-images.githubusercontent.com/30141622/78142400-7b71eb80-745f-11ea-9d74-e12dc6e23379.png)
When I added "key = cv2.waitKey(1)" again, everything was fine, 
But after the video is finished, it loops again for a while (less than the second time) before it ends. May be the delay caused by "key = cv2.waitkey (1)"?

**I do not know why I remove "key = cv2.waitKey(1)", and the detection video was not show.**
Please give my some hints for modification, Sincere thanks for you!

**Comment by jkjung-avt** [comment]
Your question is just basic programming of opencv API.  It should be easy for your to find reference online and do the studying by yourself.  For example, you could reference [this StackOverflow post](https://stackoverflow.com/questions/44854699/why-does-the-cv2-imshow-does-not-render-without-cv2-waitkey/44854945).

**Comment by sudo-wang** [comment]
Ok, Thank you all the same
