### ISSUE TITLE
Can I use tensorrt to model other yolo architecture ?

### ISSUE THREAD

**Issue by brian208579** [jkjung-avt/tensorrt_demos#79]
Hellow @jkjung-avt 
I using https://github.com/AlexeyAB/darknet training Other architectures of yolo
For example ( figure ) :
![problem](https://user-images.githubusercontent.com/43407888/78171877-ba1b9c00-7487-11ea-8eca-45ce0d2e542b.png)
Now, I want to speed up these models on tensorrt and using jetson nano inference
Can I use tensorrt to model other yolo architecture ?
By the way, have you ever used jetson tx2 to run yolov3 optimized with tensorrt ? What is it fps and resolution ?
Appreciate

**Comment by jkjung-avt** [comment]
I think it's doable.  But you'll likely have to make significant changes to [yolov3_to_onnx.py](https://github.com/jkjung-avt/tensorrt_demos/blob/master/yolov3_onnx/yolov3_to_onnx.py), [onnx_to_tensorrt](https://github.com/jkjung-avt/tensorrt_demos/blob/master/yolov3_onnx/onnx_to_tensorrt.py) and [yolov3.py](https://github.com/jkjung-avt/tensorrt_demos/blob/master/utils/yolov3.py).

**Comment by brian208579** [comment]
@jkjung-avt 
ok, I will try it, thank you very much ~
