### ISSUE TITLE
Tensor RT on custom object detection models. 

### ISSUE THREAD

**Issue by ishangupta3** [jkjung-avt/tensorrt_demos#81]
I have noticed the use of Tensor RT on pretrained object detection models. Is the process simple on custom trained object detection models ? 

Is it as easy as running through the Tensor RT python API or will there be more manual work involved?

**Comment by jkjung-avt** [comment]
Please refer to these issues (and many more in the "closed" issues of this repository):

https://github.com/jkjung-avt/tensorrt_demos/issues/76
https://github.com/jkjung-avt/tensorrt_demos/issues/75
