### ISSUE TITLE
Train yolov3 custom model performance

### ISSUE THREAD

**Issue by woo1** [jkjung-avt/tensorrt_demos#86]
I trained model with Gaussian YOLOv3 with this config file. (https://raw.githubusercontent.com/AlexeyAB/darknet/master/cfg/Gaussian_yolov3_BDD.cfg)
I read your guides for using custom model and updated sources.
**yolov3.py** 
`
filters = 87 # gausian yolo
self.output_shapes = [(1, filters, h // 32, w // 32),
                              (1, filters, h // 16, w // 16),
                              (1, filters, h //  8, w //  8)]

postprocessor_args = {
            # A list of 3 three-dimensional tuples for the YOLO masks
            'yolo_masks': [(6, 7, 8), (3, 4, 5), (0, 1, 2)],
            # A list of 9 two-dimensional tuples for the YOLO anchors
            'yolo_anchors': [(7, 10), (14, 24), (27, 43),
                             (32, 97), (57, 64), (92, 109),
                             (73, 175), (141, 178), (144, 291)],
            # Threshold for non-max suppression algorithm, float
            # value between 0 and 1
            # between 0 and 1
            'nms_threshold': 0.5,
            'yolo_input_resolution': input_shape
        }
`
`    def _reshape_output(self, output):
        """Reshape a TensorRT output from NCHW to NHWC format (with expected C=255),
        and then return it in (height,width,3,85) dimensionality after further reshaping.

        Keyword argument:
        output -- an output from a TensorRT engine after inference
        """
        output = np.transpose(output, [0, 2, 3, 1])
        _, height, width, _ = output.shape
        dim1, dim2 = height, width
        dim3 = 3
        # There are CATEGORY_NUM=80 object categories:
        # dim4 = (4 + 1 + self.category_num)
        dim4 = (8 + 1 + self.category_num) # gausian 
        return np.reshape(output, (dim1, dim2, dim3, dim4))`
and updated category_num for my own model.

But the result is so bad if i use tensorrt model.
https://drive.google.com/file/d/175fvxkVk0YZypOyIlttvK1kFdO9LARLa/view?usp=sharing
Tensorrt

https://drive.google.com/file/d/1gs11f7NqpPV2yR-A-NxQqBQPfvVsh3Qm/view?usp=sharing
darknet

We can use the only original 2 models(yolov3, yolov3-tiny) even if we update the source?

**Comment by jkjung-avt** [comment]
I only tested the code with yolov3 and tiny-yolov3.  For Gaussian YOLOv3, it's likely that you'll need to make some additional changes to the code.
