### ISSUE TITLE
libflattenconcat.so file

### ISSUE THREAD

**Issue by SahilChachere** [jkjung-avt/tensorrt_demos#87]
what is use of libflattenconcat.so, 5, 6 files in jetson nano project, and we use only one file amongst 3.

**Comment by jkjung-avt** [comment]
That is the pre-compiled library for the "FlattenConcat_TRT" plugin.  The original NVIDIA repository also has such a file: https://github.com/AastaNV/TRT_object_detection/blob/master/lib/libflattenconcat.so

The .5 and .6 files are for TensorRT 5 and TensorRT 6 respectively.  In [ssd/install.sh](https://github.com/jkjung-avt/tensorrt_demos/blob/master/ssd/install.sh#L28) I make s symbolic link depending on which version of TensorRT is used in the system.

**Comment by nhphuong91** [comment]
@jkjung-avt How can I build the pre-compiled library for the "FlattenConcat_TRT" plugin? I want to make the TensorRT 7 version of it. Thanks in advanced!

**Comment by jkjung-avt** [comment]
@nhphuong91  The "FlattenConcat_TRT" has been included in the TensorRT 7 libraries already.  You don't need to re-build it for TensorRT 7.
