### ISSUE TITLE
How to design bottleneck layers such as denseblock layer in tensorrt? 

### ISSUE THREAD

**Issue by feitiandemiaomi** [jkjung-avt/tensorrt_demos#88]
Thanks for your great repo, I want to speed up the densenet network model in tensorrt, but when writing the custom layer denseblock layer, I thought of a problem. I used the caffe model as the input. The denseblock layer has only one layer in prototxt of caffe, but it contains 8 convolution layers, and other the operation of BN, then what should I do when defining plugin? Whether to define 8 plugins for 8 convolutional layer and the BN layer separately, or only one plugin include 8 convolutional and BN,  here is the example of prototxt.
Can you give some advice，thanks for your reply.

# DenseBlock 1
layer {
  name: "DenseBlock1"
  type: "**DenseBlock**"
  bottom: "conv1"
  top: "DenseBlock1"
  denseblock_param {
    numTransition: 8
    initChannel: 64
    growthRate: 8
    Filter_Filler {
      type: "msra"
    }
    BN_Scaler_Filler {
      type: "constant"
      value: 1
    }
    BN_Bias_Filler {
      type: "constant"
      value: 0
    }
    use_dropout: false
    dropout_amount: 0.2
  }
}

**Comment by jkjung-avt** [comment]
If you are able separate the dense layer into 8 convolutions, batchnorms and element-wise adds, I think you don't need write your own plugin.  You would be able to optimize the model with TensorRT's caffe parser directly.
