### ISSUE TITLE
test on file problem

### ISSUE THREAD

**Issue by tranmanhdat** [jkjung-avt/tensorrt_demos#9]
when i test on video ( .mp4 file),it did not stop when video ended,it continued rerun video again

**Comment by jkjung-avt** [comment]
This behavior is actually by design.  If you don't want automatic looping of video files, you could modify the source code as pointed below:

https://github.com/jkjung-avt/tensorrt_demos/blob/master/utils/camera.py#L188

**Comment by tranmanhdat** [comment]
oh i changed it and i didnt remember !
