### ISSUE TITLE
multi-stream hardware decoder RTSP

### ISSUE THREAD

**Issue by PythonImageDeveloper** [jkjung-avt/tensorrt_demos#93]
Hi,
I want to do pipeline multi-stream decoder on jetson nano using H264 hardware decoder.
when I run [open_cam_rtsp()](https://github.com/jkjung-avt/tensorrt_demos/blob/master/utils/camera.py#L62), then I check to use NVDEC ro not with sudo tegrastats, I see NVDEC is active and the cpu usage is 15%, but when I put this function and run one thread, the NVDEC is became inactive and cpu usage reach to 50%, It turn out that in this state use cpu decoding. How to solve this problem?

**Comment by jkjung-avt** [comment]
This question is not directly related to code in this repository.  Please post such a question to [NVIDIA Developer forum](https://forums.developer.nvidia.com/c/agx-autonomous-machines/jetson-embedded-systems/jetson-nano/76) instead.
