### ISSUE TITLE
Could not read ONNX file by OpenCV 4.1.1

### ISSUE THREAD

**Issue by do-van-long** [jkjung-avt/tensorrt_demos#96]
Hi J.K,
I could run your TRT models in my Jetson Nano without any problem. However, when I tried different ways to perform inference on my Jetson Nano, I had problem with reading ONNX file by OpenCV.

```
import cv2
>>> net = cv2.dnn.readNetFromONNX('yolov3-416.onnx')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
cv2.error: OpenCV(4.1.1) /home/nvidia/host/build_opencv/nv_opencv/modules/dnn/src/layers/concat_layer.cpp:95: error: (-201:Incorrect size of input array) Inconsistent shape for ConcatLayer in function 'getMemoryShapes'
```
For your information, my opencv version is 4.1.1 and I could read Darket model from *.cfg and *.weights without problem (net = cv2.dnn.readNetFromDarknet('yolov3-416.cfg', 'yolov3-416.weights').

Do you have any idea for reading ONNX model by openCV?

**Comment by jkjung-avt** [comment]
My impression is that ONNX is not compatible between different versions.  You might need to figure out which ONNX version is supported by OpenCV-4.1.1.

Otherwise, I don't have any experience about what you're trying to do.
