### ISSUE TITLE
mtcnn use video file is very poor?

### ISSUE THREAD

**Issue by tianyu06030020** [jkjung-avt/tensorrt_demos#97]
@jkjung-avt hi, great work , follow your instruction I run mtcnn successfully , it's very good when I use image file ,but it's very poor when use video file. Do u know why? when use video file , almost not detect faces. thx a lot

**Comment by jkjung-avt** [comment]
I don't know.  When you said "good" and "poor", were you referring to detection result (accuracy) or FPS?

Could you provide more details about the issue?  Have you tested a few different video files (mp4, ts, etc.) and do they all exhibit the same problem?

**Comment by jkjung-avt** [comment]
Could you provide more details.  Otherwise, I'm going to close this issue due to inactivity.
