### ISSUE TITLE
threading of function open_cam_rtsp

### ISSUE THREAD

**Issue by PythonImageDeveloper** [jkjung-avt/tensorrt_demos#99]
Hi,
I want to use multi-streaming H264 hardware decoder using open_cam_rtsp funtion with jetson nano.
I passed this function into multi-thread, and it's work correctly.
My problem is that, the usage of ram gradualy increased, why? I think this is because of "appsink".
what's diffrence if we use **appsink sync=false** and **appsink**" and **appsink -e**.

**Comment by jkjung-avt** [comment]
Closing this issue since it is not very relevant to this repository.
